'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import {
  ArrowDownRight, ArrowUpRight, BarChart3, Bell, Building2, Check, ChevronDown, CircleDollarSign,
  Download, FileBarChart, FileText, Lock, Megaphone, MoreHorizontal, Plus, Save, ShieldCheck, SlidersHorizontal,
  UserPlus, Users, WalletCards,
} from 'lucide-react';
import { Modal, SectionHeading, StatCard, ViewAll } from '@/components/ui';
import { StatusBadge } from '@/components/status-badge';
import { formatDate, formatFCFA, formatNumber } from '@/lib/format';
import { FARM_STORAGE_KEYS, readLocal, writeLocal } from '@/lib/farm-storage';

type SettingsData = Record<string, string | number | boolean>;

const purchases = [
  { id: 'ACH-2026-031', supplier: 'Cameroun Grains', date: '2026-08-10', amount: 1840000, status: 'Reçue', category: 'Maïs & soja' },
  { id: 'ACH-2026-030', supplier: 'VetPro Distribution', date: '2026-08-07', amount: 285000, status: 'À payer', category: 'Santé animale' },
  { id: 'ACH-2026-029', supplier: 'EquipAgri Services', date: '2026-08-02', amount: 675000, status: 'Payée', category: 'Maintenance' },
  { id: 'ACH-2026-028', supplier: 'Cameroun Grains', date: '2026-07-28', amount: 2150000, status: 'Reçue', category: 'Matières premières' },
];

const expenses = [
  { id: 'DEP-008', label: 'Achat de maïs grain', department: 'Provenderie', date: '2026-08-10', amount: 1840000, method: 'Virement' },
  { id: 'DEP-007', label: 'Vaccins & traitements', department: 'Élevage poulets', date: '2026-08-07', amount: 285000, method: 'Mobile Money' },
  { id: 'DEP-006', label: 'Électricité du pressoir', department: 'Pressoir à huile', date: '2026-08-05', amount: 195000, method: 'Espèces' },
  { id: 'DEP-005', label: 'Entretien bâtiment B', department: 'Élevage poulets', date: '2026-08-02', amount: 420000, method: 'Virement' },
];

export function PurchasesView() {
  return <div className="fade-in space-y-7"><PageIntro eyebrow="Commerce · Approvisionnement" title="Achats" description="Gérez vos commandes, réceptions et factures fournisseurs." action="Nouvel achat" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Achats du mois" value={formatFCFA(6800000, true)} change="+7,2 %" detail="vs. juillet" icon={CircleDollarSign} tone="green" /><StatCard label="Commandes reçues" value="18" change="+4" detail="ce mois-ci" icon={Check} tone="blue" /><StatCard label="En attente de paiement" value={formatFCFA(825000, true)} change="03 factures" detail="à régler" trend="neutral" icon={WalletCards} tone="orange" /><StatCard label="Fournisseurs actifs" value="18" change="+2" detail="ce trimestre" icon={Users} tone="purple" /></div><div className="surface overflow-hidden"><div className="flex items-center justify-between border-b border-[#edf0eb] px-5 py-5 sm:px-6"><SectionHeading eyebrow="Achats récents" title="Commandes fournisseurs" /><button className="icon-btn h-8 w-8"><SlidersHorizontal size={15} /></button></div><div className="table-scroll"><table className="w-full text-left"><thead><tr className="table-head"><th>Référence</th><th>Fournisseur</th><th>Catégorie</th><th>Date</th><th>Montant</th><th>Statut</th><th /></tr></thead><tbody>{purchases.map((purchase) => <tr className="table-row table-line" key={purchase.id}><td><p className="font-bold text-ink">{purchase.id}</p></td><td>{purchase.supplier}</td><td>{purchase.category}</td><td>{formatDate(purchase.date)}</td><td className="font-bold text-ink">{formatFCFA(purchase.amount)}</td><td><StatusBadge status={purchase.status === 'Reçue' ? 'Disponible' : purchase.status === 'Payée' ? 'Payée' : 'Envoyée'} /></td><td><button className="icon-btn h-8 w-8"><MoreHorizontal size={15} /></button></td></tr>)}</tbody></table></div></div></div>;
}

export function ExpensesView() {
  const [showForm, setShowForm] = useState(false);
  return <div className="fade-in space-y-7"><PageIntro eyebrow="Finance · Suivi" title="Dépenses" description="Suivez chaque dépense et mesurez le coût réel de vos départements." action="Enregistrer une dépense" onAction={() => setShowForm(true)} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Dépenses du mois" value={6800000} change="+7,2 %" detail="vs. juillet" icon={CircleDollarSign} tone="orange" /><StatCard label="Provenderie" value={formatFCFA(3245000, true)} change="47,7 %" detail="du total" icon={BarChart3} tone="green" /><StatCard label="Élevages" value={formatFCFA(1850000, true)} change="27,2 %" detail="du total" icon={BarChart3} tone="blue" /><StatCard label="Autres charges" value={formatFCFA(1705000, true)} change="25,1 %" detail="du total" icon={WalletCards} tone="purple" /></div><div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="surface overflow-hidden"><div className="flex items-center justify-between border-b border-[#edf0eb] px-5 py-5 sm:px-6"><SectionHeading eyebrow="Journal financier" title="Dernières dépenses" /><button className="icon-btn h-8 w-8"><Download size={15} /></button></div><div className="table-scroll"><table className="w-full text-left"><thead><tr className="table-head"><th>Libellé</th><th>Département</th><th>Date</th><th>Montant</th><th>Mode</th><th /></tr></thead><tbody>{expenses.map((expense) => <tr className="table-row table-line" key={expense.id}><td><p className="font-bold text-ink">{expense.label}</p><p className="mt-1 text-[10px] text-[#9aa59f]">{expense.id}</p></td><td>{expense.department}</td><td>{formatDate(expense.date)}</td><td className="font-bold text-ink">{formatFCFA(expense.amount)}</td><td><span className="rounded-full bg-[#f1f5ef] px-2 py-1 text-[10px] font-bold text-[#718078]">{expense.method}</span></td><td><button className="icon-btn h-8 w-8"><MoreHorizontal size={15} /></button></td></tr>)}</tbody></table></div></div><div className="surface p-5 sm:p-6"><SectionHeading eyebrow="Répartition" title="Par département" /><div className="mt-5 space-y-4"><ExpenseShare label="Provenderie" value="47,7 %" amount="3,245 M" width={78} color="#72bd75" /><ExpenseShare label="Élevages" value="27,2 %" amount="1,850 M" width={54} color="#6f9fe8" /><ExpenseShare label="Pressoir" value="14,2 %" amount="965 k" width={29} color="#e9975c" /><ExpenseShare label="Autres" value="10,9 %" amount="740 k" width={22} color="#bda2e5" /></div></div></div>{showForm && <ExpenseModal onClose={() => setShowForm(false)} />}</div>;
}

export function ReportsView() {
  const [period, setPeriod] = useState('Août 2026');
  return <div className="fade-in space-y-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow mb-2">Pilotage · Analyse</p><h1 className="page-title">Rapports</h1><p className="muted mt-2 text-[13px]">Transformez vos données opérationnelles en décisions simples.</p></div><div className="flex flex-wrap gap-2"><button className="btn-secondary"><Download size={15} /> Exporter le rapport</button><label className="relative"><select value={period} onChange={(e) => setPeriod(e.target.value)} className="input-base h-10 w-[142px] appearance-none rounded-lg bg-white pr-8 text-[11px] font-semibold"><option>Août 2026</option><option>Juillet 2026</option><option>Juin 2026</option></select><ChevronDown size={13} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[#87958d]" /></label></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Revenus" value={12500000} change="+18,4 %" detail="vs. période précédente" icon={ArrowUpRight} tone="green" /><StatCard label="Dépenses" value={6800000} change="+7,2 %" detail="vs. période précédente" trend="down" icon={ArrowDownRight} tone="orange" /><StatCard label="Marge estimée" value={5700000} change="45,6 %" detail="du chiffre d’affaires" icon={BarChart3} tone="blue" /><StatCard label="Valeur du stock" value={7420000} change="+8,4 %" detail="vs. mois dernier" icon={FileBarChart} tone="purple" /></div><div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="surface p-5 sm:p-6"><SectionHeading eyebrow="Performance" title="Revenus par département" description="Contribution estimée au chiffre d’affaires du mois." /><div className="mt-7 space-y-5"><ReportBar label="Ventes de poulets" amount="5,8 M FCFA" value={85} color="#71bd76" /><ReportBar label="Huile & tourteaux" amount="3,4 M FCFA" value={62} color="#e9b45e" /><ReportBar label="Aliments animaux" amount="2,2 M FCFA" value={44} color="#6f9fe8" /><ReportBar label="Chèvrerie" amount="1,1 M FCFA" value={22} color="#b99cde" /></div></div><div className="surface p-5 sm:p-6"><SectionHeading eyebrow="Indicateurs" title="Santé de l’activité" /><div className="mt-5 space-y-3"><ReportKpi label="Taux de recouvrement" value="68 %" hint="+9 pts" tone="green" /><ReportKpi label="Mortalité poulets" value="3,8 %" hint="-0,6 pt" tone="green" /><ReportKpi label="Rendement pressoir" value="33,1 %" hint="+1,4 pt" tone="blue" /><ReportKpi label="Stock critique" value="02" hint="à traiter" tone="orange" /></div></div></div><div className="surface p-5 sm:p-6"><SectionHeading eyebrow="Exports disponibles" title="Rapports enregistrés" /><div className="mt-5 grid gap-3 md:grid-cols-3"><ReportCard title="Synthèse financière" detail="Revenus, charges & marge" /><ReportCard title="Suivi élevages" detail="Lots, mortalité & poids" /><ReportCard title="État du magasin" detail="Stock, mouvements & alertes" /></div></div></div>;
}

export function SettingsView({ unitId }: { unitId?: string }) {
  const [saved, setSaved] = useState(false);
  const [section, setSection] = useState<'company' | 'billing' | 'notifications' | 'security'>('company');
  const unitName = unitId === 'provenderie' ? 'Provenderie' : unitId === 'bio' ? 'Produits bio' : unitId === 'pressoir' ? 'Pressoir à huile' : unitId === 'stocks' ? 'Magasin central' : unitId === 'chevrerie' ? 'Chèvrerie' : unitId === 'rh' ? 'RH & administration' : unitId === 'poulets' ? 'Ferme de poulets bio' : '';
  const unitScope = unitId === 'stocks' ? 'du magasin central' : unitId === 'pressoir' ? 'du pressoir à huile' : unitId === 'bio' ? 'des produits bio' : unitId === 'provenderie' ? 'de la provenderie' : unitId === 'chevrerie' ? 'de la chèvrerie' : unitId === 'rh' ? 'des ressources humaines' : 'de la ferme de poulets bio';
  const settingsKey = `agroflux-settings-${unitId ?? 'global'}`;
  const [settings, setSettings] = useState<SettingsData>({});
  useEffect(() => { setSettings(readLocal<SettingsData>(settingsKey, {})); }, [settingsKey]);
  const saveSettings = (values: SettingsData = {}) => { const next = { ...settings, ...values, savedAt: new Date().toISOString() }; setSettings(next); writeLocal(settingsKey, next); setSaved(true); window.setTimeout(() => setSaved(false), 5000); };
  return <div className="fade-in space-y-7"><div><p className="eyebrow mb-2">{unitId ? `${unitName} · Configuration` : 'Configuration · Entreprise'}</p><h1 className="page-title">{unitId ? `Paramètres ${unitScope}` : 'Paramètres'}</h1><p className="muted mt-2 text-[13px]">{unitId ? `Les réglages et la zone de sécurité concernent uniquement l’espace ${unitScope}.` : 'Personnalisez AgroFlux pour qu’il corresponde à votre organisation.'}</p></div><div className="grid gap-5 lg:grid-cols-[250px_minmax(0,1fr)]"><div className="surface h-fit p-2"><SettingsNav icon={Building2} label="Entreprise" active={section === 'company'} onClick={() => setSection('company')} /><SettingsNav icon={Users} label="Utilisateurs" href={unitId ? `/parametres/${unitId === 'poulets' ? 'ferme' : unitId}/utilisateurs` : '/parametres/utilisateurs'} /><SettingsNav icon={Megaphone} label="Communication publique" href="/parametres/communication" /><SettingsNav icon={CircleDollarSign} label="Facturation" active={section === 'billing'} onClick={() => setSection('billing')} /><SettingsNav icon={Bell} label="Notifications" active={section === 'notifications'} onClick={() => setSection('notifications')} /><SettingsNav icon={ShieldCheck} label="Sécurité" active={section === 'security'} onClick={() => setSection('security')} /></div><div className="space-y-5">{section === 'company' && <CompanySettings key={`company-${String(settings.savedAt ?? 'default')}`} saved={saved} settings={settings} onSave={saveSettings} />}{section === 'billing' && <BillingSettings key={`billing-${String(settings.savedAt ?? 'default')}`} saved={saved} settings={settings} onSave={saveSettings} unitId={unitId} />}{section === 'notifications' && <NotificationSettings key={`notifications-${String(settings.savedAt ?? 'default')}`} saved={saved} settings={settings} onSave={saveSettings} />}{section === 'security' && <SecuritySettings key={`security-${String(settings.savedAt ?? 'default')}`} saved={saved} settings={settings} onSave={saveSettings} />}</div></div>{unitId && <UnitDangerZone unitId={unitId} unitName={unitName} />} </div>;
}

function CompanySettings({ saved, settings, onSave }: { saved: boolean; settings: SettingsData; onSave: (values?: SettingsData) => void }) { return <><form className="surface p-5 sm:p-7" onSubmit={(event) => { event.preventDefault(); onSave(formToSettings(event.currentTarget)); }}><div className="flex items-start justify-between gap-4"><div><h2 className="text-[18px] font-bold tracking-[-.035em]">Informations de l’entreprise</h2><p className="muted mt-1 text-[12px]">Elles apparaîtront sur vos factures et documents.</p></div><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#a4eb91] text-[13px] font-black text-forest">AF</div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field name="companyName" label="Nom légal de l’entreprise" value={String(settings.companyName ?? 'SOCIETE COOPERATIVE SIMPLIFIEE')} /><Field name="companyBrand" label="Nom commercial" value={String(settings.companyBrand ?? 'SCOOPS LE REVEIL')} /><Field name="companyEmail" label="Email professionnel" value={String(settings.companyEmail ?? '')} type="email" /><Field name="companyPhone" label="Téléphone" value={String(settings.companyPhone ?? '')} /><Field name="companyCity" label="Ville" value={String(settings.companyCity ?? 'Obala')} /><label className="block sm:col-span-2"><span className="field-label">Adresse</span><textarea name="companyAddress" className="input-base min-h-[78px] resize-none" defaultValue={String(settings.companyAddress ?? 'Obala, Centre, Cameroun')} /></label></div><div className="mt-6 flex justify-end"><button type="submit" className="btn-primary"><Save size={15} /> Enregistrer les modifications</button></div>{saved && <SaveNotice />}</form><div className="surface p-5 sm:p-7"><InfoCard icon={Lock} title="Sécurité et accès" text="Les utilisateurs sont créés par l’administrateur et leurs permissions sont rattachées à leur unité." /></div></>; }

function BillingSettings({ saved, settings, onSave, unitId }: { saved: boolean; settings: SettingsData; onSave: (values?: SettingsData) => void; unitId?: string }) { return <><form className="surface p-5 sm:p-7" onSubmit={(event) => { event.preventDefault(); onSave(formToSettings(event.currentTarget)); }}><SectionHeading eyebrow="Facturation" title="Préférences de facturation" description="Ces paramètres s’appliquent à l’unité active et à ses factures." /><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field name="currency" label="Devise" value={String(settings.currency ?? 'FCFA')} /><Field name="invoicePrefix" label="Préfixe des factures" value={String(settings.invoicePrefix ?? 'FAC-F')} /><label className="block"><span className="field-label">Taux de TVA par défaut</span><select name="taxRate" className="input-base" defaultValue={String(settings.taxRate ?? '18')}><option value="0">0 %</option><option value="18">18 %</option><option value="19.25">19,25 %</option></select></label><label className="block"><span className="field-label">Délai de paiement par défaut</span><select name="paymentDelay" className="input-base" defaultValue={String(settings.paymentDelay ?? '15')}><option value="0">Paiement immédiat</option><option value="15">15 jours</option><option value="30">30 jours</option><option value="45">45 jours</option></select></label></div><div className="mt-6 flex justify-end"><button type="submit" className="btn-primary"><Save size={15} /> Enregistrer la facturation</button></div>{saved && <SaveNotice />}</form>{unitId && unitId !== 'rh' && <ClientRebateSettings unitId={unitId} />}</>; }

function ClientRebateSettings({ unitId }: { unitId: string }) {
  const [rate, setRate] = useState(0);
  const [saved, setSaved] = useState(false);
  useEffect(() => {
    const all = readLocal<Record<string, { clientRebatePercent?: number }>>(FARM_STORAGE_KEYS.unitCommercialSettings, {});
    setRate(Math.max(Number(all[unitId]?.clientRebatePercent ?? 0), 0));
  }, [unitId]);
  function saveRebate() {
    const all = readLocal<Record<string, { clientRebatePercent?: number }>>(FARM_STORAGE_KEYS.unitCommercialSettings, {});
    writeLocal(FARM_STORAGE_KEYS.unitCommercialSettings, { ...all, [unitId]: { clientRebatePercent: Math.max(rate, 0) } });
    setSaved(true);
    window.setTimeout(() => setSaved(false), 4000);
  }
  return <div className="surface p-5 sm:p-7"><SectionHeading eyebrow="Avantage commercial" title="Ristourne client" description="Définissez le pourcentage appliqué aux achats cumulés des clients de cette unité." /><div className="mt-6 max-w-sm"><label className="block"><span className="field-label">Taux de ristourne (%)</span><input type="number" min="0" max="100" step="0.01" className="input-base" value={rate} onChange={(event) => setRate(Number(event.target.value))} /><p className="mt-2 text-[10px] leading-4 text-[#89968f]">Le taux sera visible dans le carnet clients et calculé à partir des factures de l’unité. Valeur initiale : 0 %.</p></label></div><div className="mt-6 flex justify-end"><button type="button" className="btn-primary" onClick={saveRebate}><Save size={15} /> Enregistrer la ristourne</button></div>{saved && <SaveNotice />}</div>;
}

function NotificationSettings({ saved, settings, onSave }: { saved: boolean; settings: SettingsData; onSave: (values?: SettingsData) => void }) { return <form className="surface p-5 sm:p-7" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onSave({ notificationsStock: form.get('notificationsStock') === 'on', notificationsInvoice: form.get('notificationsInvoice') === 'on', notificationsFollowUp: form.get('notificationsFollowUp') === 'on', notificationsHealth: form.get('notificationsHealth') === 'on' }); }}><SectionHeading eyebrow="Préférences" title="Notifications" description="Choisissez les alertes visibles dans la cloche de l’application." /><div className="mt-6 space-y-3"><ToggleSetting name="notificationsStock" title="Stock sous le seuil" detail="Alerter le responsable lorsque la quantité devient critique" checked={settings.notificationsStock !== false} /><ToggleSetting name="notificationsInvoice" title="Facture impayée" detail="Rappeler les soldes non réglés et les échéances dépassées" checked={settings.notificationsInvoice !== false} /><ToggleSetting name="notificationsFollowUp" title="Suivi quotidien manquant" detail="Signaler un bâtiment non renseigné pour la journée" checked={settings.notificationsFollowUp !== false} /><ToggleSetting name="notificationsHealth" title="Événement sanitaire" detail="Signaler une vaccination ou un traitement à venir" checked={settings.notificationsHealth !== false} /></div><div className="mt-6 flex justify-end"><button type="submit" className="btn-primary"><Save size={15} /> Enregistrer les notifications</button></div>{saved && <SaveNotice />}</form>; }

function SecuritySettings({ saved, settings, onSave }: { saved: boolean; settings: SettingsData; onSave: (values?: SettingsData) => void }) { return <><form className="surface p-5 sm:p-7" onSubmit={(event) => { event.preventDefault(); onSave(formToSettings(event.currentTarget)); }}><SectionHeading eyebrow="Accès sécurisé" title="Sécurité" description="Contrôlez la session et les accès à l’espace privé de SCOOPS LE REVEIL." /><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="block"><span className="field-label">Durée d’une session</span><select name="sessionDuration" className="input-base" defaultValue={String(settings.sessionDuration ?? '7')}><option value="1">1 jour</option><option value="7">7 jours</option><option value="30">30 jours</option></select></label><label className="block"><span className="field-label">Double validation</span><select name="twoFactor" className="input-base" defaultValue={String(settings.twoFactor ?? 'off')}><option value="off">Désactivée</option><option value="on">Activée</option></select></label></div><div className="mt-6 flex flex-wrap justify-end gap-2"><span className="rounded-lg border border-[#edf0eb] bg-[#fbfcfa] px-3 py-2.5 text-[11px] font-semibold text-[#718078]"><KeyIcon /> Mot de passe géré par l’administrateur</span><button type="submit" className="btn-primary"><Save size={15} /> Enregistrer la sécurité</button></div>{saved && <SaveNotice />}</form><div className="surface p-5 sm:p-7"><InfoCard icon={ShieldCheck} title="RLS par unité" text="Lorsque Supabase sera connecté, les règles de sécurité empêcheront un utilisateur de lire les données d’une autre unité." /></div></>; }

function UnitDangerZone({ unitId, unitName }: { unitId: string; unitName: string }) {
  const [open, setOpen] = useState(false);
  const [password, setPassword] = useState('');
  const [feedback, setFeedback] = useState('');
  async function handleDelete(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const response = await fetch('/api/admin/delete-unit', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ unitId, password }) });
    const data = await response.json();
    if (!response.ok) { setFeedback(data.error ?? 'Suppression refusée.'); return; }
    if (unitId === 'poulets') {
      window.localStorage.clear();
    } else if (unitId === 'provenderie') {
      [FARM_STORAGE_KEYS.feedRecipes, FARM_STORAGE_KEYS.feedMaterials, FARM_STORAGE_KEYS.feedProductions, FARM_STORAGE_KEYS.feedFinishedStock, FARM_STORAGE_KEYS.feedMovements, FARM_STORAGE_KEYS.unitExpenses].forEach((key) => window.localStorage.removeItem(key));
      const invoices = readLocal<Array<{ unit?: string }>>(FARM_STORAGE_KEYS.invoices, []);
      const cash = readLocal<Array<{ unit?: string }>>(FARM_STORAGE_KEYS.cashEntries, []);
      const movements = readLocal<Array<{ from: string; to: string }>>(FARM_STORAGE_KEYS.interUnitMovements, []);
      window.localStorage.setItem(FARM_STORAGE_KEYS.invoices, JSON.stringify(invoices.filter((item) => item.unit !== unitId)));
      window.localStorage.setItem(FARM_STORAGE_KEYS.cashEntries, JSON.stringify(cash.filter((item) => item.unit !== unitId)));
      window.localStorage.setItem(FARM_STORAGE_KEYS.interUnitMovements, JSON.stringify(movements.filter((item) => item.from !== unitId && item.to !== unitId)));
    } else if (unitId === 'bio') {
      [FARM_STORAGE_KEYS.bioRecipes, FARM_STORAGE_KEYS.bioMaterials, FARM_STORAGE_KEYS.bioProductions, FARM_STORAGE_KEYS.bioFinishedStock, FARM_STORAGE_KEYS.bioMovements, FARM_STORAGE_KEYS.unitExpenses].forEach((key) => window.localStorage.removeItem(key));
      const invoices = readLocal<Array<{ unit?: string }>>(FARM_STORAGE_KEYS.invoices, []);
      const cash = readLocal<Array<{ unit?: string }>>(FARM_STORAGE_KEYS.cashEntries, []);
      const movements = readLocal<Array<{ from: string; to: string }>>(FARM_STORAGE_KEYS.interUnitMovements, []);
      window.localStorage.setItem(FARM_STORAGE_KEYS.invoices, JSON.stringify(invoices.filter((item) => item.unit !== unitId)));
      window.localStorage.setItem(FARM_STORAGE_KEYS.cashEntries, JSON.stringify(cash.filter((item) => item.unit !== unitId)));
      window.localStorage.setItem(FARM_STORAGE_KEYS.interUnitMovements, JSON.stringify(movements.filter((item) => item.from !== unitId && item.to !== unitId)));
    } else if (unitId === 'chevrerie') {
      [FARM_STORAGE_KEYS.goatAnimals, FARM_STORAGE_KEYS.goatReproduction, FARM_STORAGE_KEYS.goatHealth, FARM_STORAGE_KEYS.goatFeeding, FARM_STORAGE_KEYS.goatRations, FARM_STORAGE_KEYS.goatProductions, FARM_STORAGE_KEYS.goatFinishedStock, FARM_STORAGE_KEYS.goatMovements].forEach((key) => window.localStorage.removeItem(key));
      const expenses = readLocal<Array<{ unit?: string }>>(FARM_STORAGE_KEYS.unitExpenses, []);
      window.localStorage.setItem(FARM_STORAGE_KEYS.unitExpenses, JSON.stringify(expenses.filter((item) => item.unit !== unitId)));
      const invoices = readLocal<Array<{ unit?: string }>>(FARM_STORAGE_KEYS.invoices, []);
      const cash = readLocal<Array<{ unit?: string }>>(FARM_STORAGE_KEYS.cashEntries, []);
      const movements = readLocal<Array<{ from: string; to: string }>>(FARM_STORAGE_KEYS.interUnitMovements, []);
      window.localStorage.setItem(FARM_STORAGE_KEYS.invoices, JSON.stringify(invoices.filter((item) => item.unit !== unitId)));
      window.localStorage.setItem(FARM_STORAGE_KEYS.cashEntries, JSON.stringify(cash.filter((item) => item.unit !== unitId)));
      window.localStorage.setItem(FARM_STORAGE_KEYS.interUnitMovements, JSON.stringify(movements.filter((item) => item.from !== unitId && item.to !== unitId)));
    } else if (unitId === 'rh') {
      [FARM_STORAGE_KEYS.rhEmployees, FARM_STORAGE_KEYS.rhAttendance, FARM_STORAGE_KEYS.rhLeave, FARM_STORAGE_KEYS.rhPayroll, FARM_STORAGE_KEYS.rhDocuments].forEach((key) => window.localStorage.removeItem(key));
    } else if (unitId === 'stocks') {
      [FARM_STORAGE_KEYS.centralStock, FARM_STORAGE_KEYS.centralMovements, FARM_STORAGE_KEYS.centralCategories, FARM_STORAGE_KEYS.centralOrders].forEach((key) => window.localStorage.removeItem(key));
      const invoices = readLocal<Array<{ unit?: string }>>(FARM_STORAGE_KEYS.invoices, []);
      const cash = readLocal<Array<{ unit?: string }>>(FARM_STORAGE_KEYS.cashEntries, []);
      const movements = readLocal<Array<{ from: string; to: string }>>(FARM_STORAGE_KEYS.interUnitMovements, []);
      window.localStorage.setItem(FARM_STORAGE_KEYS.invoices, JSON.stringify(invoices.filter((item) => item.unit !== unitId)));
      window.localStorage.setItem(FARM_STORAGE_KEYS.cashEntries, JSON.stringify(cash.filter((item) => item.unit !== unitId)));
      window.localStorage.setItem(FARM_STORAGE_KEYS.interUnitMovements, JSON.stringify(movements.filter((item) => item.from !== unitId && item.to !== unitId)));
    }
    if (unitId !== 'poulets') {
      const clients = readLocal<Array<{ unit?: string }>>(FARM_STORAGE_KEYS.unitClients, []);
      const suppliers = readLocal<Array<{ unit?: string }>>(FARM_STORAGE_KEYS.unitSuppliers, []);
      window.localStorage.setItem(FARM_STORAGE_KEYS.unitClients, JSON.stringify(clients.filter((item) => item.unit !== unitId)));
      window.localStorage.setItem(FARM_STORAGE_KEYS.unitSuppliers, JSON.stringify(suppliers.filter((item) => item.unit !== unitId)));
    }
    window.dispatchEvent(new CustomEvent('agroflux-data-updated', { detail: null }));
    document.cookie = 'agroflux_active_unit=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/';
    setOpen(false);
    setPassword('');
    window.location.assign('/selection-unite');
  }
  return <div className="surface border border-[#f0cfcc] bg-[#fff8f7] p-5 sm:p-7"><div className="flex items-start gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#fdeceb] text-[#bd5c5c]">!</span><div className="min-w-0 flex-1"><h2 className="text-[15px] font-bold text-[#9d4f50]">Zone dangereuse · {unitName}</h2><p className="mt-1 max-w-2xl text-[11px] leading-5 text-[#a66d6e]">Supprime les données locales de cette unité. Cette action ne supprime pas les données des autres unités.</p><button className="mt-4 rounded-lg border border-[#e9bcbc] bg-white px-3 py-2 text-[11px] font-bold text-[#b45353] hover:bg-[#fff0ef]" onClick={() => setOpen(true)}>Supprimer les données de {unitName.toLowerCase()}</button>{feedback && <p className="mt-3 text-[11px] font-bold text-[#b45353]">{feedback}</p>}</div></div><Modal open={open} onClose={() => setOpen(false)} title={`Supprimer les données · ${unitName}`}><form onSubmit={handleDelete} className="space-y-5"><p className="text-[12px] leading-5 text-[#8e5b5d]">Cette suppression est définitive pour l’unité {unitName.toLowerCase()}. Confirmez avec le mot de passe dédié.</p><label className="block"><span className="field-label">Mot de passe de confirmation</span><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="input-base" required /></label><div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={() => setOpen(false)}>Annuler</button><button className="rounded-lg bg-[#bd5c5c] px-4 py-2.5 text-[11px] font-bold text-white hover:bg-[#a84c4c]">Supprimer définitivement</button></div></form></Modal></div>;
}

function InfoCard({ icon: Icon, title, text }: { icon: typeof Lock; title: string; text: string }) { return <div className="flex items-start gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[#edf3ff] text-[#6084be]"><Icon size={16} /></span><div><h2 className="text-[15px] font-bold text-ink">{title}</h2><p className="muted mt-1 text-[11px] leading-5">{text}</p></div></div>; }
function CheckSetting({ title, detail, checked }: { title: string; detail: string; checked?: boolean }) { return <div className="rounded-xl border border-[#edf0eb] p-3"><div className="flex items-center gap-2"><span className={`flex h-5 w-5 items-center justify-center rounded-md ${checked ? 'bg-[#dff3d9] text-[#5b9d5b]' : 'bg-[#f0f3ef] text-[#9aa59f]'}`}>{checked && <Check size={13} />}</span><p className="text-[11px] font-bold text-ink">{title}</p></div><p className="mt-2 text-[10px] text-[#8b9891]">{detail}</p></div>; }
function ToggleSetting({ name, title, detail, checked }: { name: string; title: string; detail: string; checked?: boolean }) { return <label className="flex items-center gap-3 rounded-xl border border-[#edf0eb] p-3.5"><span className={`relative flex h-5 w-9 rounded-full ${checked ? 'bg-[#71bd76]' : 'bg-[#dfe6df]'}`}><input name={name} type="checkbox" defaultChecked={checked} className="sr-only" /><span className={`absolute top-1 h-3 w-3 rounded-full bg-white transition ${checked ? 'right-1' : 'left-1'}`} /></span><span><span className="block text-[11px] font-bold text-ink">{title}</span><span className="mt-1 block text-[10px] text-[#8b9891]">{detail}</span></span></label>; }
function formToSettings(form: HTMLFormElement): SettingsData { const result: SettingsData = {}; new FormData(form).forEach((value, key) => { result[key] = String(value); }); return result; }
function SaveNotice() { return <div role="status" aria-live="polite" className="mt-4 flex items-center justify-end gap-2 rounded-xl border border-[#cde8c7] bg-[#effaeb] px-3 py-2.5 text-[11px] font-bold text-[#4d8f51]"><Check size={14} /> Modifications enregistrées dans cet espace.</div>; }
function KeyIcon() { return <span className="text-[14px]">⚿</span>; }

function PageIntro({ eyebrow, title, description, action, onAction }: { eyebrow: string; title: string; description: string; action: string; onAction?: () => void }) { return <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow mb-2">{eyebrow}</p><h1 className="page-title">{title}</h1><p className="muted mt-2 text-[13px]">{description}</p></div><button className="btn-primary" onClick={onAction}><Plus size={16} /> {action}</button></div>; }
function ExpenseShare({ label, value, amount, width, color }: { label: string; value: string; amount: string; width: number; color: string }) { return <div><div className="mb-2 flex justify-between text-[11px] font-semibold"><span className="text-[#66766d]">{label}</span><span className="text-ink">{amount} <span className="ml-1 text-[10px] text-[#8d9992]">({value})</span></span></div><div className="h-2 overflow-hidden rounded-full bg-[#eff2ee]"><div className="h-full rounded-full" style={{ width: `${width}%`, background: color }} /></div></div>; }
function ExpenseModal({ onClose }: { onClose: () => void }) { return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-[#102d23]/35 p-4 backdrop-blur-[3px]" onMouseDown={onClose}><form onSubmit={(e) => { e.preventDefault(); onClose(); }} onMouseDown={(e) => e.stopPropagation()} className="surface w-full max-w-lg p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">Enregistrer une dépense</h2><button type="button" className="icon-btn h-8 w-8 text-lg" onClick={onClose}>×</button></div><div className="space-y-4"><Field label="Libellé" value="" placeholder="Ex. Achat de maïs grain" /><div className="grid gap-4 sm:grid-cols-2"><Field label="Montant" value="" placeholder="0 FCFA" /><label className="block"><span className="field-label">Département</span><select className="input-base"><option>Provenderie</option><option>Élevage poulets</option><option>Pressoir à huile</option><option>Magasin</option></select></label></div><Field label="Date" value="2026-08-11" type="date" /><div className="flex justify-end gap-2 pt-2"><button type="button" className="btn-secondary" onClick={onClose}>Annuler</button><button className="btn-primary" type="submit"><Check size={15} /> Enregistrer</button></div></div></form></div>; }
function ReportBar({ label, amount, value, color }: { label: string; amount: string; value: number; color: string }) { return <div><div className="mb-2 flex items-center justify-between"><span className="text-[12px] font-semibold text-[#66766d]">{label}</span><span className="text-[12px] font-bold text-ink">{amount}</span></div><div className="h-3 overflow-hidden rounded-full bg-[#eef2ed]"><div className="h-full rounded-full" style={{ width: `${value}%`, background: color }} /></div></div>; }
function ReportKpi({ label, value, hint, tone }: { label: string; value: string; hint: string; tone: 'green' | 'blue' | 'orange' }) { const cls = { green: 'text-[#5b9d5b] bg-[#edf8ea]', blue: 'text-[#5c82be] bg-[#edf3ff]', orange: 'text-[#be7839] bg-[#fff2e2]' }; return <div className="flex items-center justify-between rounded-xl border border-[#edf0eb] p-3"><div><p className="text-[11px] font-semibold text-[#718078]">{label}</p><p className="mt-1 text-[17px] font-black tracking-[-.04em] text-ink">{value}</p></div><span className={`rounded-lg px-2 py-1 text-[10px] font-bold ${cls[tone]}`}>{hint}</span></div>; }
function ReportCard({ title, detail }: { title: string; detail: string }) { return <button className="group flex items-center gap-3 rounded-xl border border-[#edf0eb] p-4 text-left transition hover:border-[#cde3cc] hover:bg-[#f8fcf6]"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#edf8ea] text-[#5c9d5a]"><FileText size={16} /></span><span className="min-w-0 flex-1"><span className="block text-[11px] font-bold text-ink">{title}</span><span className="mt-1 block text-[10px] text-[#89968f]">{detail}</span></span><ArrowUpRight size={14} className="text-[#8da698] transition group-hover:text-[#5a9d5b]" /></button>; }
function SettingsNav({ icon: Icon, label, active, href, onClick }: { icon: typeof Building2; label: string; active?: boolean; href?: string; onClick?: () => void }) { const className = `flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-[11px] font-bold transition ${active ? 'bg-[#edf8e9] text-[#4e8f52]' : 'text-[#718078] hover:bg-[#f5f8f3] hover:text-ink'}`; return href ? <Link href={href} className={className}><Icon size={15} />{label}</Link> : <button type="button" className={className} onClick={onClick}><Icon size={15} />{label}</button>; }
function Field({ name, label, value, type = 'text', placeholder }: { name?: string; label: string; value: string; type?: string; placeholder?: string }) { return <label className="block"><span className="field-label">{label}</span><input name={name} className="input-base" type={type} defaultValue={value} placeholder={placeholder} /></label>; }
