'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowDownRight, ArrowLeft, ArrowUpRight, Boxes, Check, Download, Edit3, Factory, History, Package, Plus, Search, Settings2, Truck, Wrench } from 'lucide-react';
import { formatDate, formatFCFA, formatNumber } from '@/lib/format';
import { FARM_STORAGE_KEYS, readLocal, writeLocal } from '@/lib/farm-storage';
import { EmptyState } from '@/components/empty-state';
import { Modal, SectionHeading, StatCard } from '@/components/ui';
import { StatusBadge } from '@/components/status-badge';

type CentralTab = 'dashboard' | 'stock' | 'machines' | 'movements' | 'inventory';
type CentralType = 'Produit agricole' | 'Machine agricole' | 'Autre';
type CentralItem = { id: string; name: string; type: CentralType; category: string; unit: string; quantity: number; min: number; purchasePrice: number; supplier: string; location: string; serial?: string; condition?: string; expiryDate?: string };
type CentralMovement = { id: string; date: string; type: 'Entrée' | 'Sortie' | 'Ajustement'; itemId: string; itemName: string; quantity: number; unit: string; delta: number; reason: string; recipient: string; reference: string; operator: string };

export function CentralStoreView({ initialTab = 'dashboard' }: { initialTab?: CentralTab }) {
  const [tab, setTab] = useState(initialTab);
  const [items, setItems] = useState<CentralItem[]>([]);
  const [movements, setMovements] = useState<CentralMovement[]>([]);
  const [hydrated, setHydrated] = useState(false);
  const [itemOpen, setItemOpen] = useState(false);
  const [movementOpen, setMovementOpen] = useState(false);
  const [editingItem, setEditingItem] = useState<CentralItem | null>(null);
  const [query, setQuery] = useState('');
  const [feedback, setFeedback] = useState('');

  useEffect(() => {
    setItems(readLocal(FARM_STORAGE_KEYS.centralStock, [] as CentralItem[]));
    setMovements(readLocal(FARM_STORAGE_KEYS.centralMovements, [] as CentralMovement[]));
    setHydrated(true);
  }, []);
  useEffect(() => { if (hydrated) writeLocal(FARM_STORAGE_KEYS.centralStock, items); }, [items, hydrated]);
  useEffect(() => { if (hydrated) writeLocal(FARM_STORAGE_KEYS.centralMovements, movements); }, [movements, hydrated]);

  const visibleItems = useMemo(() => items.filter((item) => `${item.id} ${item.name} ${item.category} ${item.type}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  const lowStock = items.filter((item) => item.quantity <= item.min);
  const machines = items.filter((item) => item.type === 'Machine agricole');
  const stockValue = items.reduce((sum, item) => sum + item.quantity * item.purchasePrice, 0);
  const monthMovements = movements.filter((movement) => movement.date.startsWith('2026-08'));

  function notify(message: string) { setFeedback(message); window.setTimeout(() => setFeedback(''), 4000); }
  function saveItem(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const item: CentralItem = { id: editingItem?.id ?? `MAG-${Date.now()}`, name: String(form.get('name') ?? '').trim(), type: String(form.get('type') ?? 'Produit agricole') as CentralType, category: String(form.get('category') ?? 'Autre'), unit: String(form.get('unit') ?? 'unité'), quantity: Number(form.get('quantity') ?? 0), min: Number(form.get('min') ?? 0), purchasePrice: Number(form.get('purchasePrice') ?? 0), supplier: String(form.get('supplier') ?? '').trim(), location: String(form.get('location') ?? 'Magasin central').trim(), serial: String(form.get('serial') ?? '').trim(), condition: String(form.get('condition') ?? 'Bon').trim(), expiryDate: String(form.get('expiryDate') ?? '') };
    if (!item.name || item.quantity < 0 || item.min < 0 || item.purchasePrice < 0) return;
    setItems((current) => editingItem ? current.map((old) => old.id === item.id ? item : old) : [item, ...current]);
    setEditingItem(null);
    setItemOpen(false);
    notify(`${item.name} a été ${editingItem ? 'modifié' : 'ajouté'} au magasin central.`);
  }
  function saveMovement(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const itemId = String(form.get('itemId') ?? '');
    const type = String(form.get('type') ?? 'Entrée') as CentralMovement['type'];
    const quantity = Number(form.get('quantity') ?? 0);
    const item = items.find((current) => current.id === itemId);
    if (!item || quantity <= 0) return;
    const newQuantity = type === 'Entrée' ? item.quantity + quantity : type === 'Sortie' ? item.quantity - quantity : quantity;
    if (newQuantity < 0) { notify(`Stock insuffisant : il reste ${formatNumber(item.quantity)} ${item.unit}.`); return; }
    const movement: CentralMovement = { id: `MVT-MAG-${Date.now()}`, date: String(form.get('date') ?? '2026-08-13'), type, itemId, itemName: item.name, quantity: type === 'Ajustement' ? Math.abs(newQuantity - item.quantity) : quantity, unit: item.unit, delta: newQuantity - item.quantity, reason: String(form.get('reason') ?? 'Mouvement de magasin').trim(), recipient: String(form.get('recipient') ?? '').trim(), reference: String(form.get('reference') ?? '').trim(), operator: 'Administrateur' };
    setItems((current) => current.map((old) => old.id === item.id ? { ...old, quantity: newQuantity } : old));
    setMovements((current) => [movement, ...current]);
    setMovementOpen(false);
    notify(`${type} enregistrée pour ${item.name}.`);
  }
  function exportInventory() {
    const csv = ['SCOOPS LE REVEIL', 'Inventaire magasin central', '', 'Référence;Article;Type;Catégorie;Quantité;Seuil;Prix achat;Valeur;Emplacement;État', ...items.map((item) => [item.id, item.name, item.type, item.category, `${item.quantity} ${item.unit}`, `${item.min} ${item.unit}`, item.purchasePrice, item.quantity * item.purchasePrice, item.location, item.condition ?? ''].join(';'))].join('\n');
    const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: 'text/csv;charset=utf-8' })); link.download = 'inventaire-magasin-central.csv'; link.click(); URL.revokeObjectURL(link.href); notify('L’inventaire du magasin a été exporté.');
  }

  return <div className="fade-in space-y-7"><Header tab={tab} onNewItem={() => { setEditingItem(null); setItemOpen(true); }} onNewMovement={() => setMovementOpen(true)} onExport={exportInventory} /><div className="flex items-start gap-3 rounded-xl border border-[#dcebdd] bg-[#f5faf2] px-4 py-3 text-[11px] text-[#5b8f60]"><Boxes size={15} /> Le magasin central est dédié à 90 % aux produits agricoles et aux machines agricoles. Les autres articles peuvent aussi être enregistrés dans la catégorie Autre.</div>{feedback && <div className="flex items-center gap-2 rounded-xl border border-[#cde8c7] bg-[#effaeb] px-4 py-3 text-[12px] font-semibold text-[#4d8f51]"><Check size={14} />{feedback}</div>}{tab === 'dashboard' && <Dashboard items={items} machines={machines} lowStock={lowStock} stockValue={stockValue} movements={monthMovements} />} {tab === 'stock' && <StockView items={visibleItems} query={query} setQuery={setQuery} onEdit={(item) => { setEditingItem(item); setItemOpen(true); }} />} {tab === 'machines' && <MachinesView items={machines} onEdit={(item) => { setEditingItem(item); setItemOpen(true); }} />} {tab === 'movements' && <MovementsView movements={movements} />} {tab === 'inventory' && <InventoryView items={items} movements={movements} onExport={exportInventory} />}
    <Modal open={itemOpen} onClose={() => { setItemOpen(false); setEditingItem(null); }} title={editingItem ? 'Modifier un article du magasin' : 'Nouvel article du magasin'}><form onSubmit={saveItem} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><label className="block sm:col-span-2"><span className="field-label">Nom de l’article</span><input name="name" className="input-base" defaultValue={editingItem?.name ?? ''} placeholder="Ex. Semences de maïs ou motopompe" required /></label><label className="block"><span className="field-label">Type</span><select name="type" className="input-base" defaultValue={editingItem?.type ?? 'Produit agricole'}><option>Produit agricole</option><option>Machine agricole</option><option>Autre</option></select></label><label className="block"><span className="field-label">Catégorie</span><input name="category" className="input-base" defaultValue={editingItem?.category ?? ''} placeholder="Semences, engrais, équipement..." required /></label><label className="block"><span className="field-label">Unité</span><select name="unit" className="input-base" defaultValue={editingItem?.unit ?? 'unité'}><option>unité</option><option>kg</option><option>sac</option><option>litre</option><option>carton</option></select></label><label className="block"><span className="field-label">Prix d’achat unitaire (FCFA)</span><input name="purchasePrice" type="number" min="0" className="input-base" defaultValue={editingItem?.purchasePrice ?? 0} required /></label><label className="block"><span className="field-label">Quantité actuelle</span><input name="quantity" type="number" min="0" step="0.01" className="input-base" defaultValue={editingItem?.quantity ?? 0} required /></label><label className="block"><span className="field-label">Seuil d’alerte</span><input name="min" type="number" min="0" step="0.01" className="input-base" defaultValue={editingItem?.min ?? 0} required /></label><label className="block"><span className="field-label">Fournisseur</span><input name="supplier" className="input-base" defaultValue={editingItem?.supplier ?? ''} placeholder="Nom du fournisseur" /></label><label className="block"><span className="field-label">Emplacement</span><input name="location" className="input-base" defaultValue={editingItem?.location ?? 'Magasin central'} /></label><label className="block"><span className="field-label">État / condition</span><input name="condition" className="input-base" defaultValue={editingItem?.condition ?? 'Bon'} /></label><label className="block"><span className="field-label">N° série ou immatriculation</span><input name="serial" className="input-base" defaultValue={editingItem?.serial ?? ''} placeholder="Pour une machine" /></label></div><div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={() => setItemOpen(false)}>Annuler</button><button className="btn-primary" type="submit"><Check size={15} /> Enregistrer</button></div></form></Modal>
    <Modal open={movementOpen} onClose={() => setMovementOpen(false)} title="Nouveau mouvement magasin"><form onSubmit={saveMovement} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><label className="block"><span className="field-label">Type</span><select name="type" className="input-base"><option>Entrée</option><option>Sortie</option><option>Ajustement</option></select></label><label className="block"><span className="field-label">Date</span><input name="date" type="date" defaultValue="2026-08-13" className="input-base" required /></label></div><label className="block"><span className="field-label">Article</span><select name="itemId" className="input-base" required><option value="">Choisir un article</option>{items.map((item) => <option key={item.id} value={item.id}>{item.name} · {formatNumber(item.quantity)} {item.unit}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label className="block"><span className="field-label">Quantité</span><input name="quantity" type="number" min="0.01" step="0.01" className="input-base" required /></label><label className="block"><span className="field-label">Bénéficiaire / unité</span><input name="recipient" className="input-base" placeholder="Ferme, provenderie, responsable..." /></label></div><label className="block"><span className="field-label">Motif</span><input name="reason" className="input-base" placeholder="Achat, distribution, inventaire..." required /></label><label className="block"><span className="field-label">Référence / justificatif</span><input name="reference" className="input-base" placeholder="Bon, reçu, numéro de demande..." /></label><div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={() => setMovementOpen(false)}>Annuler</button><button className="btn-primary" type="submit"><Check size={15} /> Enregistrer le mouvement</button></div></form></Modal>
  </div>;
}

function Header({ tab, onNewItem, onNewMovement, onExport }: { tab: CentralTab; onNewItem: () => void; onNewMovement: () => void; onExport: () => void }) { const labels: Record<CentralTab, string> = { dashboard: 'Dashboard magasin central', stock: 'Stock central', machines: 'Machines agricoles', movements: 'Mouvements magasin', inventory: 'Inventaire général' }; return <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><Link href="/selection-unite" className="mb-4 inline-flex items-center gap-2 text-[11px] font-bold text-[#6c8176] hover:text-forest">← Changer d’unité</Link><p className="eyebrow mb-2">Unité · Magasin central</p><h1 className="page-title">{labels[tab]}</h1><p className="muted mt-2 max-w-2xl text-[13px] leading-5">Centralisez les produits agricoles, les machines agricoles et les autres articles de SCOOPS LE REVEIL.</p></div><div className="flex flex-wrap gap-2">{tab !== 'inventory' && <button className="btn-secondary" onClick={onNewItem}><Plus size={15} /> Nouvel article</button>}{tab !== 'inventory' && <button className="btn-primary" onClick={onNewMovement}><Plus size={15} /> Nouveau mouvement</button>}{tab === 'inventory' && <button className="btn-primary" onClick={onExport}><Download size={15} /> Exporter inventaire</button>}</div></div>; }

function Dashboard({ items, machines, lowStock, stockValue, movements }: { items: CentralItem[]; machines: CentralItem[]; lowStock: CentralItem[]; stockValue: number; movements: CentralMovement[] }) { return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Références" value={String(items.length)} change="catalogue central" detail="produits et équipements" icon={Boxes} tone="green" /><StatCard label="Valeur du stock" value={stockValue} change="prix d’achat" detail="estimation actuelle" icon={Package} tone="blue" /><StatCard label="Machines agricoles" value={String(machines.length)} change="parc central" detail="équipements suivis" icon={Wrench} tone="orange" /><StatCard label="Alertes stock" value={String(lowStock.length)} change={lowStock.length ? 'À traiter' : 'Aucune alerte'} detail="seuils configurés" icon={Settings2} tone="purple" /></div><div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="surface p-5 sm:p-6"><SectionHeading eyebrow="Stock central" title="Articles prioritaires" description="Le magasin est principalement consacré aux produits et machines agricoles." /><div className="mt-5 space-y-3">{lowStock.length ? lowStock.slice(0, 6).map((item) => <div className="flex items-center gap-3 rounded-xl border border-[#f0dfc4] bg-[#fff9ed] p-3" key={item.id}><Boxes size={16} className="text-[#bd7737]" /><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-bold text-ink">{item.name}</p><p className="mt-1 text-[10px] text-[#9a7651]">{formatNumber(item.quantity)} {item.unit} · seuil {formatNumber(item.min)}</p></div><strong className="text-[10px] text-[#bd7737]">{formatFCFA(item.purchasePrice)}</strong></div>) : <EmptyState title="Aucune alerte de stock" description="Les références du magasin sont au-dessus de leurs seuils." />}</div></div><div className="surface p-5 sm:p-6"><SectionHeading eyebrow="Traçabilité" title="Derniers mouvements" /><div className="mt-5 space-y-3">{movements.length ? movements.slice(0, 5).map((movement) => <div className="flex items-center gap-3 rounded-xl border border-[#edf0eb] p-3" key={movement.id}><span className={`flex h-8 w-8 items-center justify-center rounded-lg ${movement.delta >= 0 ? 'bg-[#edf8ea] text-[#5b9d5b]' : 'bg-[#fff2e2] text-[#bd7737]'}`}>{movement.delta >= 0 ? <ArrowUpRight size={15} /> : <ArrowDownRight size={15} />}</span><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-bold text-ink">{movement.itemName}</p><p className="mt-1 text-[10px] text-[#8b9891]">{formatDate(movement.date)} · {movement.type}</p></div><strong className={movement.delta >= 0 ? 'text-[11px] text-[#5b9d5b]' : 'text-[11px] text-[#bd7737]'}>{movement.delta > 0 ? '+' : ''}{formatNumber(movement.delta)} {movement.unit}</strong></div>) : <p className="py-8 text-center text-[11px] text-[#89968f]">Aucun mouvement enregistré.</p>}</div></div></div></div>; }

function StockView({ items, query, setQuery, onEdit }: { items: CentralItem[]; query: string; setQuery: (value: string) => void; onEdit: (item: CentralItem) => void }) { return <div className="surface overflow-hidden"><div className="border-b border-[#edf0eb] px-5 pb-4 pt-5 sm:px-6"><div className="flex items-center justify-between"><SectionHeading eyebrow="Inventaire permanent" title="Tous les articles du magasin" description="90 % de l’activité concerne les produits et machines agricoles." /><div className="relative min-w-[230px]"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#9aa69f]" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="input-base h-9 rounded-lg bg-[#fbfcfa] pl-9 text-[11px]" placeholder="Rechercher..." /></div></div></div><div className="table-scroll"><table className="w-full text-left"><thead><tr className="table-head"><th>Article</th><th>Type</th><th>Catégorie</th><th>Quantité</th><th>Seuil</th><th>Prix achat</th><th>Valeur</th><th>État</th><th /></tr></thead><tbody>{items.length ? items.map((item) => <tr className="table-row table-line" key={item.id}><td><p className="font-bold text-ink">{item.name}</p><p className="mt-1 text-[10px] text-[#9aa59f]">{item.id} · {item.location}</p></td><td>{item.type}</td><td>{item.category}</td><td className={item.quantity <= item.min ? 'font-bold text-[#bd7737]' : 'font-bold text-ink'}>{formatNumber(item.quantity)} {item.unit}</td><td>{formatNumber(item.min)} {item.unit}</td><td>{formatFCFA(item.purchasePrice)}</td><td>{formatFCFA(item.quantity * item.purchasePrice)}</td><td><StatusBadge status={item.quantity <= item.min ? 'Faible' : 'Normal'} /></td><td><button className="icon-btn h-8 w-8" onClick={() => onEdit(item)} aria-label="Modifier"><Edit3 size={14} /></button></td></tr>) : <tr><td colSpan={9} className="px-6 py-14 text-center text-[11px] text-[#89968f]">Aucun article enregistré.</td></tr>}</tbody></table></div></div>; }

function MachinesView({ items, onEdit }: { items: CentralItem[]; onEdit: (item: CentralItem) => void }) { return <div className="surface overflow-hidden"><div className="border-b border-[#edf0eb] px-5 py-5 sm:px-6"><SectionHeading eyebrow="Parc matériel" title="Machines agricoles" description="Suivez les équipements, leur état, leur numéro de série et leur emplacement." /></div><div className="table-scroll"><table className="w-full text-left"><thead><tr className="table-head"><th>Machine</th><th>Catégorie</th><th>N° série</th><th>État</th><th>Emplacement</th><th>Valeur</th><th /></tr></thead><tbody>{items.length ? items.map((item) => <tr className="table-row table-line" key={item.id}><td className="font-bold text-ink">{item.name}</td><td>{item.category}</td><td>{item.serial || '—'}</td><td>{item.condition || '—'}</td><td>{item.location}</td><td>{formatFCFA(item.purchasePrice)}</td><td><button className="icon-btn h-8 w-8" onClick={() => onEdit(item)} aria-label="Modifier la machine"><Edit3 size={14} /></button></td></tr>) : <tr><td colSpan={7} className="px-6 py-14 text-center text-[11px] text-[#89968f]">Aucune machine agricole enregistrée.</td></tr>}</tbody></table></div></div>; }

function MovementsView({ movements }: { movements: CentralMovement[] }) { return <div className="surface overflow-hidden"><div className="border-b border-[#edf0eb] px-5 py-5 sm:px-6"><SectionHeading eyebrow="Traçabilité" title="Mouvements du magasin central" description="Entrées, sorties, ajustements et distributions vers les unités." /></div><div className="table-scroll"><table className="w-full text-left"><thead><tr className="table-head"><th>Date</th><th>Type</th><th>Article</th><th>Variation</th><th>Bénéficiaire</th><th>Motif</th><th>Référence</th></tr></thead><tbody>{movements.length ? movements.map((movement) => <tr className="table-row table-line" key={movement.id}><td>{formatDate(movement.date)}</td><td>{movement.type}</td><td>{movement.itemName}</td><td className={movement.delta >= 0 ? 'font-bold text-[#5b9d5b]' : 'font-bold text-[#bd7737]'}>{movement.delta > 0 ? '+' : ''}{formatNumber(movement.delta)} {movement.unit}</td><td>{movement.recipient || '—'}</td><td>{movement.reason}</td><td>{movement.reference || '—'}</td></tr>) : <tr><td colSpan={7} className="px-6 py-14 text-center text-[11px] text-[#89968f]">Aucun mouvement enregistré.</td></tr>}</tbody></table></div></div>; }

function InventoryView({ items, movements, onExport }: { items: CentralItem[]; movements: CentralMovement[]; onExport: () => void }) { const entries = movements.filter((movement) => movement.type === 'Entrée').reduce((sum, movement) => sum + movement.quantity, 0); const exits = movements.filter((movement) => movement.type === 'Sortie').reduce((sum, movement) => sum + movement.quantity, 0); return <div className="space-y-5"><div className="flex justify-end"><button className="btn-primary" onClick={onExport}><Download size={15} /> Exporter l’inventaire</button></div><div className="grid gap-4 sm:grid-cols-3"><InventorySummary label="Références" value={String(items.length)} detail="catalogue central" icon={Boxes} /><InventorySummary label="Entrées cumulées" value={formatNumber(entries)} detail="unités enregistrées" icon={ArrowUpRight} /><InventorySummary label="Sorties cumulées" value={formatNumber(exits)} detail="unités distribuées" icon={ArrowDownRight} /></div><div className="surface p-5 sm:p-6"><SectionHeading eyebrow="Inventaire" title="Valeur totale du magasin" description="La valeur est calculée sur les prix d’achat renseignés." /><p className="mt-5 text-[30px] font-black text-forest">{formatFCFA(items.reduce((sum, item) => sum + item.quantity * item.purchasePrice, 0))}</p></div></div>; }
function InventorySummary({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: typeof Boxes }) { return <div className="surface flex items-center gap-3 p-4"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#edf8ea] text-[#5b9d5b]"><Icon size={16} /></span><div><p className="text-[10px] font-semibold text-[#849188]">{label}</p><p className="mt-1 text-[17px] font-black text-ink">{value}</p><p className="mt-1 text-[9px] text-[#9aa59f]">{detail}</p></div></div>; }
