'use client';

import { useMemo, useState, type FormEvent } from 'react';
import Link from 'next/link';
import {
  Activity, AlertTriangle, ArrowRight, ChevronDown, CirclePlus, ClipboardCheck, Download, Filter,
  MoreHorizontal, Package, PawPrint, Plus, Search, SlidersHorizontal, Sprout, Trash2, Wheat, Droplets, Truck, FlaskConical,
} from 'lucide-react';
import { bioProductions, feedProductions, goats, inventory, oilProductions, poultryLots, customers, suppliers, units } from '@/lib/data';
import { formatDate, formatFCFA, formatNumber, formatPercent } from '@/lib/format';
import { EmptyState } from '@/components/empty-state';
import { MiniProgress, SectionHeading, StatCard, ViewAll } from '@/components/ui';
import { StatusBadge } from '@/components/status-badge';
import { Modal } from '@/components/ui';

type ModuleKey = 'poulets' | 'chevrerie' | 'provenderie' | 'bio' | 'pressoir' | 'stocks' | 'clients' | 'fournisseurs';

const configs: Record<ModuleKey, { eyebrow: string; title: string; description: string; action: string; search: string; icon: typeof PawPrint }> = {
  poulets: { eyebrow: 'Opérations · Élevage', title: 'Élevage de poulets', description: 'Pilotez vos lots, de l’arrivée des poussins jusqu’à la vente.', action: 'Nouveau lot', search: 'Rechercher un lot...', icon: PawPrint },
  chevrerie: { eyebrow: 'Opérations · Élevage', title: 'Chèvrerie', description: 'Suivez chaque animal, sa santé et l’évolution de votre cheptel.', action: 'Ajouter une chèvre', search: 'Rechercher un animal...', icon: Sprout },
  provenderie: { eyebrow: 'Opérations · Production', title: 'Provenderie', description: 'Gérez vos recettes, productions et transferts d’aliments.', action: 'Lancer une production', search: 'Rechercher une production...', icon: Wheat },
  bio: { eyebrow: 'Opérations · Fabrication', title: 'Produits bio', description: 'Fabriquez et suivez les produits naturels destinés à vos élevages de poulets.', action: 'Nouvelle fabrication', search: 'Rechercher une fabrication...', icon: FlaskConical },
  pressoir: { eyebrow: 'Opérations · Production', title: 'Pressoir à huile', description: 'Suivez les rendements, l’huile et les tourteaux produits.', action: 'Nouveau pressage', search: 'Rechercher un lot de pressage...', icon: Droplets },
  stocks: { eyebrow: 'Ressources · Magasin', title: 'Magasin & stocks', description: 'Centralisez vos matières premières, produits et mouvements.', action: 'Mouvement de stock', search: 'Rechercher un produit...', icon: Package },
  clients: { eyebrow: 'Commerce · Carnet', title: 'Clients', description: 'Retrouvez vos clients et l’historique de leurs transactions.', action: 'Nouveau client', search: 'Rechercher un client...', icon: PawPrint },
  fournisseurs: { eyebrow: 'Commerce · Carnet', title: 'Fournisseurs', description: 'Gérez vos partenaires d’approvisionnement et leurs soldes.', action: 'Nouveau fournisseur', search: 'Rechercher un fournisseur...', icon: Truck },
};

export function OperationsView({ module }: { module: ModuleKey }) {
  const config = configs[module];
  const [query, setQuery] = useState('');
  const [tab, setTab] = useState('Tout');
  const [unitFilter, setUnitFilter] = useState('Toutes les unités');
  const [modalOpen, setModalOpen] = useState(false);
  const [feedback, setFeedback] = useState('');
  const Icon = config.icon;
  const tabs = module === 'poulets' ? ['Tout', 'En cours', 'Prêt à vendre', 'Terminés'] : module === 'stocks' ? ['Tous', 'Stock faible', 'Rupture', 'Normal'] : module === 'provenderie' || module === 'bio' ? ['Toutes', 'Disponible', 'En production'] : ['Tout', 'Actifs', 'Archives'];

  const filtered = useMemo(() => {
    const q = query.toLowerCase();
    if (module === 'poulets') return poultryLots.filter((item) => `${item.id} ${item.name} ${item.status}`.toLowerCase().includes(q) && (tab === 'Tout' || (tab === 'Terminés' ? item.status === 'Terminé' : item.status === tab)));
    if (module === 'chevrerie') return goats.filter((item) => `${item.id} ${item.name} ${item.breed} ${item.status}`.toLowerCase().includes(q));
    if (module === 'provenderie') return feedProductions.filter((item) => `${item.id} ${item.recipe} ${item.status}`.toLowerCase().includes(q) && (tab === 'Toutes' || item.status === tab));
    if (module === 'bio') return bioProductions.filter((item) => `${item.id} ${item.product} ${item.target} ${item.status}`.toLowerCase().includes(q) && (tab === 'Toutes' || item.status === tab));
    if (module === 'pressoir') return oilProductions.filter((item) => `${item.id} ${item.seed} ${item.status}`.toLowerCase().includes(q));
    if (module === 'stocks') return inventory.filter((item) => `${item.id} ${item.name} ${item.category}`.toLowerCase().includes(q) && (tab === 'Tous' || (tab === 'Stock faible' ? item.status === 'Faible' : tab === 'Rupture' ? item.status === 'Critique' : item.status === tab)) && (unitFilter === 'Toutes les unités' || item.unitId === units.find((unit) => unit.label === unitFilter)?.id));
    if (module === 'clients') return customers.filter((item) => `${item.id} ${item.name} ${item.contact}`.toLowerCase().includes(q));
    return suppliers.filter((item) => `${item.id} ${item.name} ${item.contact}`.toLowerCase().includes(q));
  }, [module, query, tab, unitFilter]);

  function handleModalSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setModalOpen(false);
    setFeedback(`${config.action} enregistré avec succès dans les données locales.`);
    window.setTimeout(() => setFeedback(''), 3500);
  }

  return <div className="fade-in space-y-7">
    <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow mb-2">{config.eyebrow}</p><h1 className="page-title">{config.title}</h1><p className="muted mt-2 max-w-2xl text-[13px] leading-5">{config.description}</p></div><div className="flex flex-wrap gap-2"><button className="btn-secondary"><Download size={15} /> Exporter</button><button className="btn-primary" onClick={() => setModalOpen(true)}><Plus size={16} /> {config.action}</button></div></div>
    {feedback && <div className="flex items-center gap-2 rounded-xl border border-[#cde8c7] bg-[#effaeb] px-4 py-3 text-[12px] font-semibold text-[#4d8f51]"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-[#72bf70] text-white">✓</span>{feedback}</div>}
    <Stats module={module} />
    {module === 'poulets' && <PoultrySnapshot />}
    {module === 'stocks' && <StockBanner />}
    {module === 'provenderie' && <ProductionSnapshot />}
    {module === 'bio' && <BioSnapshot />}
    {module === 'pressoir' && <PressSnapshot />}

    <div className="surface overflow-hidden"><div className="flex flex-col gap-4 border-b border-[#edf0eb] px-5 pb-4 pt-5 sm:px-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-1 overflow-x-auto rounded-xl bg-[#f4f7f2] p-1">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-[11px] font-bold transition ${tab === item ? 'bg-white text-forest shadow-sm' : 'text-[#87948c] hover:text-ink'}`}>{item}</button>)}</div><div className="flex flex-wrap gap-2"><div className="relative min-w-[210px] flex-1 sm:flex-none"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#9aa69f]" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="input-base h-9 rounded-lg bg-[#fbfcfa] pl-9 text-[11px]" placeholder={config.search} /></div>{module === 'stocks' && <label className="relative"><select value={unitFilter} onChange={(e) => setUnitFilter(e.target.value)} className="input-base h-9 w-[158px] appearance-none rounded-lg bg-[#fbfcfa] pr-8 text-[11px] font-semibold"><option>Toutes les unités</option>{units.map((unit) => <option key={unit.id}>{unit.label}</option>)}</select><ChevronDown size={13} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[#87958d]" /></label>}<button className="icon-btn h-9 w-9"><SlidersHorizontal size={15} /></button></div></div></div><div className="table-scroll">{renderTable(module, filtered)}</div>{filtered.length === 0 && <div className="px-5 py-10"><EmptyState title="Aucun résultat" description="Aucune donnée ne correspond à votre recherche ou à ce filtre." /></div>}<div className="flex items-center justify-between border-t border-[#edf0eb] px-5 py-4 text-[11px] text-[#8a9790] sm:px-6"><span>{filtered.length} élément{filtered.length > 1 ? 's' : ''}</span><div className="flex items-center gap-2"><span className="rounded-lg bg-[#edf8e9] px-2.5 py-1.5 font-bold text-[#4d9352]">Page 1</span><button className="text-[#5b8c61] hover:underline">Suivant →</button></div></div></div>
    <Modal open={modalOpen} onClose={() => setModalOpen(false)} title={config.action}><form onSubmit={handleModalSubmit} className="space-y-4"><p className="muted text-[12px] leading-5">Cette action utilise actuellement les données locales de démonstration. Elle sera connectée à Supabase dans la prochaine étape.</p><label className="block"><span className="field-label">Nom ou référence</span><input className="input-base" placeholder={module === 'poulets' ? 'Ex. Lot Ross 308 — Bâtiment A' : 'Saisir une référence'} required /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block"><span className="field-label">Date</span><input type="date" defaultValue="2026-08-11" className="input-base" /></label><label className="block"><span className="field-label">Responsable</span><input className="input-base" placeholder="Nom du responsable" /></label></div><label className="block"><span className="field-label">Note</span><textarea className="input-base min-h-[82px] resize-none" placeholder="Ajouter une note facultative..." /></label><div className="flex justify-end gap-2 pt-2"><button type="button" className="btn-secondary" onClick={() => setModalOpen(false)}>Annuler</button><button type="submit" className="btn-primary"><CirclePlus size={15} /> Enregistrer</button></div></form></Modal>
  </div>;
}

function Stats({ module }: { module: ModuleKey }) {
  if (module === 'poulets') return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Animaux en élevage" value="1 969" change="+12,8 %" detail="vs. mois dernier" icon={PawPrint} tone="green" /><StatCard label="Lots actifs" value="04 lots" change="+1 lot" detail="ce mois-ci" icon={ClipboardCheck} tone="blue" /><StatCard label="Mortalité moyenne" value="3,8 %" change="-0,6 %" detail="bonne évolution" icon={Activity} tone="orange" /><StatCard label="Poids moyen" value="1,64 kg" change="+240 g" detail="sur 30 jours" icon={Sprout} tone="purple" /></div>;
  if (module === 'chevrerie') return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Cheptel total" value="24 têtes" change="+4" detail="naissances ce trimestre" icon={Sprout} tone="green" /><StatCard label="Femelles" value="16" change="66,7 %" detail="du cheptel" icon={PawPrint} tone="blue" /><StatCard label="Reproducteurs" value="03" change="Stable" detail="actifs" trend="neutral" icon={Activity} tone="orange" /><StatCard label="Suivis santé" value="02" change="À surveiller" detail="cette semaine" trend="neutral" icon={ClipboardCheck} tone="purple" /></div>;
  if (module === 'provenderie') return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Production du mois" value="4 200 kg" change="+16,2 %" detail="vs. juillet" icon={Wheat} tone="green" /><StatCard label="Recettes actives" value="06" change="2 élevages" detail="approvisionnés" icon={ClipboardCheck} tone="blue" /><StatCard label="Coût moyen / kg" value={formatFCFA(575)} change="-4,1 %" detail="ce mois-ci" trend="neutral" icon={CirclePlus} tone="orange" /><StatCard label="Matières critiques" value="02" change="À réapprovisionner" detail="maïs & soja" trend="neutral" icon={AlertTriangle} tone="purple" /></div>;
  if (module === 'bio') return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Fabrication du mois" value="950 kg/L" change="+21,5 %" detail="vs. juillet" icon={FlaskConical} tone="green" /><StatCard label="Recettes bio actives" value="05" change="3 produits" detail="pour les poulets" icon={ClipboardCheck} tone="blue" /><StatCard label="Coût moyen" value={formatFCFA(618)} change="-3,2 %" detail="par unité produite" trend="neutral" icon={CirclePlus} tone="orange" /><StatCard label="Lots approvisionnés" value="04" change="Ce mois-ci" detail="élevage poulets" icon={PawPrint} tone="purple" /></div>;
  if (module === 'pressoir') return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Huile produite" value="1 941 L" change="+12,4 %" detail="ce mois-ci" icon={Droplets} tone="green" /><StatCard label="Tourteaux" value="3 465 kg" change="+9,8 %" detail="sous-produits" icon={Wheat} tone="blue" /><StatCard label="Rendement moyen" value="33,1 %" change="+1,4 pt" detail="vs. juillet" icon={Activity} tone="orange" /><StatCard label="Lots pressés" value="03" change="En hausse" detail="ce mois-ci" icon={ClipboardCheck} tone="purple" /></div>;
  if (module === 'stocks') return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Valeur du stock" value={7420000} change="+8,4 %" detail="vs. mois dernier" icon={Package} tone="green" /><StatCard label="Références" value="128" change="+12" detail="produits actifs" icon={ClipboardCheck} tone="blue" /><StatCard label="Stock faible" value="02" change="À traiter" detail="cette semaine" trend="neutral" icon={AlertTriangle} tone="orange" /><StatCard label="Mouvements" value="86" change="Ce mois-ci" detail="entrées & sorties" icon={Activity} tone="purple" /></div>;
  if (module === 'clients') return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Clients actifs" value="42" change="+6" detail="ce trimestre" icon={PawPrint} tone="green" /><StatCard label="Ventes du mois" value={12500000} change="+18,4 %" detail="vs. juillet" icon={CirclePlus} tone="blue" /><StatCard label="À encaisser" value={formatFCFA(4220000, true)} change="4 factures" detail="en attente" trend="neutral" icon={Activity} tone="orange" /><StatCard label="Nouveaux clients" value="08" change="Ce mois-ci" detail="bon rythme" icon={Sprout} tone="purple" /></div>;
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Fournisseurs actifs" value="18" change="+2" detail="ce trimestre" icon={PawPrint} tone="green" /><StatCard label="Achats du mois" value={formatFCFA(6800000, true)} change="+7,2 %" detail="vs. juillet" icon={CirclePlus} tone="blue" /><StatCard label="À payer" value={formatFCFA(825000, true)} change="3 factures" detail="en attente" trend="neutral" icon={Activity} tone="orange" /><StatCard label="Évalués" value="14 / 18" change="78 %" detail="du carnet" icon={ClipboardCheck} tone="purple" /></div>;
}

function renderTable(module: ModuleKey, items: any[]) {
  if (module === 'poulets') return <table className="w-full text-left"><thead><tr className="table-head"><th>Lot</th><th>Arrivée</th><th>Effectif</th><th>Poids moyen</th><th>Mortalité</th><th>Statut</th><th /></tr></thead><tbody>{items.map((item) => <tr className="table-row table-line" key={item.id}><td><p className="font-bold text-ink">{item.name}</p><p className="mt-1 text-[10px] text-[#9aa59f]">{item.id} · {item.age} jours</p></td><td>{formatDate(item.start)}</td><td><strong className="text-ink">{formatNumber(item.alive)}</strong><span className="ml-1 text-[10px] text-[#9aa59f]">/ {formatNumber(item.initial)}</span></td><td>{item.weight.toFixed(2).replace('.', ',')} kg</td><td><span className={item.mortality > 4 ? 'text-[#c76662]' : 'text-[#5a9a5a]'}>{formatPercent(item.mortality)}</span></td><td><StatusBadge status={item.status} /></td><td><MoreButton /></td></tr>)}</tbody></table>;
  if (module === 'chevrerie') return <table className="w-full text-left"><thead><tr className="table-head"><th>Animal</th><th>Race</th><th>Sexe</th><th>Âge</th><th>Poids</th><th>État</th><th /></tr></thead><tbody>{items.map((item) => <tr className="table-row table-line" key={item.id}><td><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#edf8ea] text-[#5c9f59]"><Sprout size={15} /></span><div><p className="font-bold text-ink">{item.name}</p><p className="mt-1 text-[10px] text-[#9aa59f]">{item.id} · {item.status}</p></div></div></td><td>{item.breed}</td><td>{item.sex}</td><td>{item.age}</td><td>{item.weight} kg</td><td><span className={item.health === 'Bon' ? 'text-[#5a9a5a]' : 'text-[#bd7b3d]'}>{item.health}</span></td><td><MoreButton /></td></tr>)}</tbody></table>;
  if (module === 'provenderie') return <table className="w-full text-left"><thead><tr className="table-head"><th>Production</th><th>Date</th><th>Quantité</th><th>Coût de production</th><th>Statut</th><th /></tr></thead><tbody>{items.map((item) => <tr className="table-row table-line" key={item.id}><td><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#fff3e4] text-[#be7839]"><Wheat size={15} /></span><div><p className="font-bold text-ink">{item.recipe}</p><p className="mt-1 text-[10px] text-[#9aa59f]">{item.id}</p></div></div></td><td>{formatDate(item.date)}</td><td><strong className="text-ink">{formatNumber(item.quantity)}</strong> {item.unit}</td><td>{formatFCFA(item.cost)}</td><td><StatusBadge status={item.status} /></td><td><MoreButton /></td></tr>)}</tbody></table>;
  if (module === 'bio') return <table className="w-full text-left"><thead><tr className="table-head"><th>Produit bio</th><th>Date</th><th>Quantité</th><th>Destination</th><th>Coût de fabrication</th><th>Statut</th><th /></tr></thead><tbody>{items.map((item) => <tr className="table-row table-line" key={item.id}><td><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#edf8ea] text-[#579b5a]"><FlaskConical size={15} /></span><div><p className="font-bold text-ink">{item.product}</p><p className="mt-1 text-[10px] text-[#9aa59f]">{item.id} · {item.ingredients}</p></div></div></td><td>{formatDate(item.date)}</td><td><strong className="text-ink">{formatNumber(item.quantity)}</strong> {item.unit}</td><td>{item.target}</td><td>{formatFCFA(item.cost)}</td><td><StatusBadge status={item.status} /></td><td><MoreButton /></td></tr>)}</tbody></table>;
  if (module === 'pressoir') return <table className="w-full text-left"><thead><tr className="table-head"><th>Lot de pressage</th><th>Date</th><th>Entrée</th><th>Huile</th><th>Tourteaux</th><th>Rendement</th><th /></tr></thead><tbody>{items.map((item) => <tr className="table-row table-line" key={item.id}><td><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#fff6d8] text-[#ac861f]"><Droplets size={15} /></span><div><p className="font-bold text-ink">{item.seed}</p><p className="mt-1 text-[10px] text-[#9aa59f]">{item.id}</p></div></div></td><td>{formatDate(item.date)}</td><td>{formatNumber(item.input)} kg</td><td>{formatNumber(item.oil)} L</td><td>{formatNumber(item.cake)} kg</td><td><span className="font-bold text-[#5a9a5a]">{item.yield} %</span></td><td><MoreButton /></td></tr>)}</tbody></table>;
  if (module === 'stocks') return <table className="w-full text-left"><thead><tr className="table-head"><th>Produit</th><th>Catégorie</th><th>Unité propriétaire</th><th>Quantité disponible</th><th>Seuil minimum</th><th>Emplacement</th><th>Statut</th><th /></tr></thead><tbody>{items.map((item) => <tr className="table-row table-line" key={item.id}><td><div className="flex items-center gap-3"><span className="h-8 w-1.5 rounded-full" style={{ background: item.color }} /><div><p className="font-bold text-ink">{item.name}</p><p className="mt-1 text-[10px] text-[#9aa59f]">{item.id}</p></div></div></td><td>{item.category}</td><td><span className="rounded-full bg-[#f1f5ef] px-2 py-1 text-[10px] font-bold text-[#66766d]">{units.find((unit) => unit.id === item.unitId)?.shortLabel}</span></td><td><strong className="text-ink">{formatNumber(item.quantity)}</strong> {item.unit}</td><td>{formatNumber(item.min)} {item.unit}</td><td>{item.location}</td><td><StatusBadge status={item.status} /></td><td><MoreButton /></td></tr>)}</tbody></table>;
  if (module === 'clients') return <table className="w-full text-left"><thead><tr className="table-head"><th>Client</th><th>Contact</th><th>Segment</th><th>Total ventes</th><th>Solde dû</th><th /></tr></thead><tbody>{items.map((item) => <tr className="table-row table-line" key={item.id}><td><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[#e9f3ff] text-[10px] font-black text-[#5e83bf]">{item.name.slice(0,2).toUpperCase()}</span><div><p className="font-bold text-ink">{item.name}</p><p className="mt-1 text-[10px] text-[#9aa59f]">{item.id}</p></div></div></td><td><p>{item.contact}</p><p className="mt-1 text-[10px] text-[#9aa59f]">{item.phone}</p></td><td><span className="rounded-full bg-[#f1f5ef] px-2 py-1 text-[10px] font-bold text-[#718078]">{item.tag}</span></td><td>{formatFCFA(item.total)}</td><td className={item.balance > 0 ? 'font-bold text-[#c5743c]' : 'font-semibold text-[#5a9a5a]'}>{item.balance > 0 ? formatFCFA(item.balance) : 'À jour'}</td><td><MoreButton /></td></tr>)}</tbody></table>;
  return <table className="w-full text-left"><thead><tr className="table-head"><th>Fournisseur</th><th>Contact</th><th>Catégorie</th><th>Solde à payer</th><th>Évaluation</th><th /></tr></thead><tbody>{items.map((item) => <tr className="table-row table-line" key={item.id}><td><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[#fff2e2] text-[10px] font-black text-[#bd783a]">{item.name.slice(0,2).toUpperCase()}</span><div><p className="font-bold text-ink">{item.name}</p><p className="mt-1 text-[10px] text-[#9aa59f]">{item.id}</p></div></div></td><td><p>{item.contact}</p><p className="mt-1 text-[10px] text-[#9aa59f]">{item.phone}</p></td><td>{item.category}</td><td className={item.balance > 0 ? 'font-bold text-[#c5743c]' : 'font-semibold text-[#5a9a5a]'}>{item.balance > 0 ? formatFCFA(item.balance) : 'À jour'}</td><td><span className="text-[#c28c3f]">★★★★★</span></td><td><MoreButton /></td></tr>)}</tbody></table>;
}

function MoreButton() { return <button className="icon-btn h-8 w-8"><MoreHorizontal size={15} /></button>; }

function PoultrySnapshot() { return <div className="surface p-5 sm:p-6"><SectionHeading eyebrow="Suivi du cycle" title="Progression des lots" description="Un aperçu rapide de l’avancement de vos lots actifs." /><div className="mt-5 grid gap-4 md:grid-cols-3">{poultryLots.slice(0, 3).map((lot) => <div className="rounded-2xl border border-[#edf0eb] p-4" key={lot.id}><div className="flex items-center justify-between"><p className="text-[11px] font-bold text-ink">{lot.id}</p><StatusBadge status={lot.status} /></div><p className="mt-2 truncate text-[11px] text-[#728079]">{lot.name}</p><div className="mt-4"><MiniProgress value={lot.status === 'Terminé' ? 100 : Math.min(lot.age / 56 * 100, 100)} color={lot.status === 'Prêt à vendre' ? 'orange' : 'green'} label="Avancement" right={`${Math.min(Math.round(lot.age / 56 * 100), 100)}%`} /></div></div>)}</div></div>; }
function StockBanner() { return <div className="flex flex-col gap-4 rounded-2xl border border-[#f4dfbf] bg-[#fff9ec] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#ffeccf] text-[#bd793c]"><AlertTriangle size={18} /></span><div><h2 className="text-[14px] font-bold text-[#85552c]">2 références nécessitent votre attention</h2><p className="mt-1 text-[11px] leading-5 text-[#a4754d]">Réapprovisionnez le maïs grain et les vaccins avant les prochaines productions.</p></div></div><button className="btn-secondary border-[#f2d8b7] bg-white text-[#a86631]">Créer une commande <ArrowRight size={14} /></button></div>; }
function ProductionSnapshot() { return <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="surface p-5 sm:p-6"><SectionHeading eyebrow="Recettes" title="Production à venir" action={<ViewAll href="/provenderie" label="Voir les recettes" />} /><div className="mt-5 space-y-4"><RecipeRow name="Poulet croissance" usage="Lots LP-26-004 & LP-26-003" value={72} color="green" /><RecipeRow name="Caprin entretien" usage="Chèvrerie · 24 têtes" value={48} color="blue" /><RecipeRow name="Démarrage poulet" usage="Prochain lot prévu" value={24} color="orange" /></div></div><div className="surface bg-forest p-5 text-white sm:p-6"><p className="eyebrow text-[#91af9f]">Coût de production moyen</p><p className="mt-3 text-[28px] font-black tracking-[-.06em]">575 <span className="text-[13px] font-semibold text-[#a8c4ae]">FCFA / kg</span></p><p className="mt-2 text-[11px] leading-5 text-[#a8c4ae]">-4,1 % par rapport au mois dernier</p><div className="mt-5 h-1.5 rounded-full bg-white/10"><div className="h-full w-[68%] rounded-full bg-[#a4eb91]" /></div><p className="mt-2 text-right text-[10px] text-[#94b29d]">Objectif : 540 FCFA / kg</p></div></div>; }
function RecipeRow({ name, usage, value, color }: { name: string; usage: string; value: number; color: 'green' | 'blue' | 'orange' }) { return <div><div className="mb-2 flex justify-between gap-3"><div><p className="text-[12px] font-bold text-ink">{name}</p><p className="mt-1 text-[10px] text-[#8b9891]">{usage}</p></div><span className="text-[12px] font-bold text-ink">{value}%</span></div><MiniProgress value={value} color={color} /></div>; }
function BioSnapshot() { return <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="surface p-5 sm:p-6"><SectionHeading eyebrow="Fabrication naturelle" title="Produits destinés aux poulets" description="Suivez les préparations bio utilisées par vos lots d’élevage." action={<ViewAll href="/produits-bio" label="Voir l’historique" />} /><div className="mt-5 space-y-4">{bioProductions.map((item) => <div className="flex items-center gap-3 rounded-xl border border-[#edf0eb] p-3" key={item.id}><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[#edf8ea] text-[#579b5a]"><FlaskConical size={16} /></span><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><p className="truncate text-[11px] font-bold text-ink">{item.product}</p><span className="whitespace-nowrap text-[11px] font-bold text-ink">{formatNumber(item.quantity)} {item.unit}</span></div><p className="mt-1 truncate text-[10px] text-[#8b9891]">{item.ingredients}</p><div className="mt-2"><MiniProgress value={item.status === 'En production' ? 58 : 100} color={item.status === 'En production' ? 'orange' : 'green'} /></div></div></div>)}</div></div><div className="surface bg-forest p-5 text-white sm:p-6"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#a4eb91] text-forest"><FlaskConical size={19} /></div><p className="eyebrow mt-5 text-[#91af9f]">Traçabilité</p><h2 className="mt-2 text-[19px] font-bold tracking-[-.04em]">Des recettes maîtrisées, lot après lot.</h2><p className="mt-2 text-[11px] leading-5 text-[#a8c4ae]">Chaque fabrication est liée à ses ingrédients, son coût et au lot de poulets approvisionné.</p><button className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[#a4eb91] px-3.5 py-2.5 text-[11px] font-bold text-forest hover:bg-[#baf1aa]">Gérer les recettes <ArrowRight size={14} /></button></div></div>; }
function PressSnapshot() { return <div className="surface overflow-hidden p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><SectionHeading eyebrow="Rendement" title="Performance du pressoir" description="Rendement moyen par matière première ce mois-ci." /><span className="rounded-lg bg-[#fff6da] px-2.5 py-1.5 text-[10px] font-bold text-[#a57c1f]">3 lots pressés</span></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><PressMetric seed="Soja" value={34} color="#d5a83e" /><PressMetric seed="Coton" value={31.4} color="#7a9fd7" /><PressMetric seed="Arachide" value={38.2} color="#77b771" /></div></div>; }
function PressMetric({ seed, value, color }: { seed: string; value: number; color: string }) { return <div className="rounded-2xl border border-[#edf0eb] p-4"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-[12px] font-bold text-ink"><span className="h-2.5 w-2.5 rounded-full" style={{ background: color }} />{seed}</span><span className="text-[12px] font-bold text-[#5b9c59]">{value}%</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#f0f3ee]"><div className="h-full rounded-full" style={{ width: `${value * 2.3}%`, background: color }} /></div><p className="mt-2 text-[10px] text-[#8b9891]">rendement huile</p></div>; }
