'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import type { LucideIcon } from 'lucide-react';
import { AlertTriangle, ArrowLeftRight, ArrowRight, BarChart3, Boxes, CalendarDays, Check, ChevronDown, CircleDollarSign, ClipboardCheck, Droplets, FlaskConical, MoreHorizontal, Package, PawPrint, Plus, Receipt, Sprout, ShieldCheck, Thermometer, TrendingUp, Users, WalletCards, Wheat } from 'lucide-react';
import { bioProductions, feedProductions, inventory, oilProductions, poultryBuildings, poultryDailyRecords, poultryHealthEvents, poultryLots, poultryTransfers, units } from '@/lib/data';
import { formatDate, formatFCFA, formatNumber, formatPercent } from '@/lib/format';
import { FARM_STORAGE_KEYS, readLocal, subscribeToFarmData } from '@/lib/farm-storage';
import { loadFarmSnapshot } from '@/lib/farm-calculations';
import { ProvenderieView } from '@/components/provenderie-view';
import { CentralStoreView } from '@/components/central-store-view';
import { GoatFarmView } from '@/components/goat-farm-view';
import { HRView } from '@/components/hr-view';
import { MiniProgress, SectionHeading, StatCard, ViewAll } from '@/components/ui';
import { PeriodSelector } from '@/components/period-selector';
import { DateRangePicker } from '@/components/date-range-picker';
import { StatusBadge } from '@/components/status-badge';
import { DashboardView } from '@/components/dashboard-view';

type UnitId = 'poulets' | 'provenderie' | 'bio' | 'pressoir' | 'stocks' | 'chevrerie' | 'rh' | 'global';

const configs: Record<Exclude<UnitId, 'global'>, { eyebrow: string; title: string; description: string; icon: LucideIcon; color: string; actionHref: string; actionLabel: string }> = {
  poulets: { eyebrow: 'Unité · Ferme bio', title: 'Dashboard élevage de poulets bio', description: 'Pilotez vos bâtiments, bandes, suivis quotidiens, santé et performances de l’élevage bio.', icon: PawPrint, color: '#5b9d5b', actionHref: '/poulets/bandes', actionLabel: 'Gérer les bandes' },
  provenderie: { eyebrow: 'Unité · Production', title: 'Dashboard provenderie', description: 'Suivez les recettes, matières premières, productions et transferts d’aliments.', icon: Wheat, color: '#bd7737', actionHref: '/provenderie', actionLabel: 'Gérer la production' },
  bio: { eyebrow: 'Unité · Fabrication', title: 'Dashboard produits bio', description: 'Suivez la fabrication et la traçabilité des produits naturels destinés aux élevages.', icon: FlaskConical, color: '#8b73b8', actionHref: '/produits-bio', actionLabel: 'Gérer les fabrications' },
  pressoir: { eyebrow: 'Unité · Production', title: 'Dashboard pressoir à huile', description: 'Pilotez les pressages, les rendements, l’huile et les tourteaux par lot.', icon: Droplets, color: '#a9801e', actionHref: '/pressoir', actionLabel: 'Gérer les pressages' },
  stocks: { eyebrow: 'Unité · Ressources', title: 'Dashboard magasin central', description: 'Gérez un magasin dédié à 90 % aux produits agricoles et aux machines agricoles, avec une catégorie Autre pour le complément.', icon: Boxes, color: '#6385bd', actionHref: '/stocks', actionLabel: 'Gérer le stock' },
  chevrerie: { eyebrow: 'Unité · Élevage', title: 'Dashboard chèvrerie', description: 'Gérez les animaux, la reproduction, la santé, l’alimentation, les productions et les mouvements du cheptel caprin.', icon: Sprout, color: '#5b9d5b', actionHref: '/chevrerie', actionLabel: 'Gérer le cheptel' },
  rh: { eyebrow: 'Unité · Administration', title: 'Dashboard RH & administration', description: 'Gérez le personnel, les présences, les congés, la paie et les documents des six unités de SCOOPS LE REVEIL.', icon: Users, color: '#8b73b8', actionHref: '/rh/personnel', actionLabel: 'Gérer le personnel' },
};

export function UnitDashboardView({ unitId }: { unitId: string }) {
  if (unitId === 'global') return <DirectionDashboardGuard />;
  const config = configs[unitId as Exclude<UnitId, 'global'>] ?? configs.poulets;
  if (unitId === 'poulets') return <PoultryUnitDashboard config={config} />;
  if (unitId === 'provenderie') return <ProvenderieView initialTab="dashboard" kind="provenderie" />;
  if (unitId === 'bio') return <ProvenderieView initialTab="dashboard" kind="bio" />;
  if (unitId === 'pressoir') return <ProvenderieView initialTab="dashboard" kind="pressoir" />;
  if (unitId === 'stocks') return <CentralStoreView initialTab="dashboard" />;
  if (unitId === 'chevrerie') return <GoatFarmView initialTab="dashboard" />;
  if (unitId === 'rh') return <HRView initialTab="dashboard" />;
  return <UnitComingSoonView config={config} />;
}

function DirectionDashboardGuard() {
  const [allowed, setAllowed] = useState<boolean | null>(null);
  useEffect(() => {
    const cookieRole = typeof document !== 'undefined' ? document.cookie.split('; ').find((item) => item.startsWith('agroflux_role='))?.split('=').slice(1).join('=') : '';
    const role = decodeURIComponent(cookieRole || readLocal(FARM_STORAGE_KEYS.currentUserRole, 'Administratrice')).trim().toUpperCase();
    setAllowed(['PDG', 'DG', 'ADMINISTRATRICE'].includes(role));
  }, []);
  if (allowed === null) return null;
  if (allowed) return <DashboardView />;
  return <div className="fade-in space-y-7"><div><p className="eyebrow mb-2">Accès direction</p><h1 className="page-title">Vue consolidée non accessible</h1><p className="muted mt-2 max-w-2xl text-[13px] leading-5">Cette vue est réservée aux utilisateurs ayant le rôle PDG ou DG.</p></div><div className="surface p-7"><div className="flex items-start gap-3 rounded-xl border border-[#eadff3] bg-[#f8f4fc] p-5 text-[12px] leading-5 text-[#70578f]"><ShieldCheck size={20} className="mt-0.5 shrink-0" /><span>Vous pouvez continuer à travailler dans l’unité qui vous est attribuée. Si votre rôle doit être modifié, contactez l’administrateur.</span></div><Link href="/selection-unite" className="btn-primary mt-6">Retour à la sélection des unités <ArrowRight size={15} /></Link></div></div>;
}

function UnitComingSoonView({ config }: { config: UnitConfig }) {
  const Icon = config.icon;
  return <div className="fade-in space-y-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><Link href="/selection-unite" className="mb-4 inline-flex items-center gap-2 text-[11px] font-bold text-[#6c8176] hover:text-forest"><ChevronDown size={14} className="rotate-90" /> Changer d’unité</Link><p className="eyebrow mb-2">{config.eyebrow}</p><h1 className="page-title">{config.title}</h1><p className="muted mt-2 max-w-2xl text-[13px] leading-5">{config.description}</p></div></div><div className="surface relative overflow-hidden p-8 sm:p-12"><div className="relative z-10 max-w-xl"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#edf8e9] text-[#5b9d5b]"><Icon size={26} /></span><p className="eyebrow mt-7">Développement par étape</p><h2 className="mt-3 text-[30px] font-bold leading-[1.02] tracking-[-.06em] text-forest sm:text-[42px]">Cette unité sera développée <span className="landing-serif text-[#e9975c]">après la ferme.</span></h2><p className="muted mt-5 max-w-lg text-[13px] leading-6">Pour le moment, nous construisons entièrement l’unité ferme de poulets : bâtiments, bandes, suivi quotidien, santé, stocks et ventes. Cette unité conservera son propre dashboard lorsqu’elle sera ouverte.</p><div className="mt-7 flex flex-wrap gap-2"><Link href="/dashboard/poulets" className="btn-primary"><PawPrint size={15} /> Ouvrir le dashboard ferme</Link><Link href="/selection-unite" className="btn-secondary">Retour à la sélection</Link></div></div><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full border-[36px] border-[#a4eb91]/20" /><div className="absolute -bottom-28 right-40 h-56 w-56 rounded-full border-[22px] border-[#e9975c]/10" /></div></div>;
}

type UnitConfig = typeof configs.poulets;

function UnitHeader({ config, onPeriodChange, rangeFrom, rangeTo, onRangeChange }: { config: UnitConfig; onPeriodChange?: (value: string) => void; rangeFrom?: string; rangeTo?: string; onRangeChange?: (from: string, to: string) => void }) {
  return <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><Link href="/selection-unite" className="mb-4 inline-flex items-center gap-2 text-[11px] font-bold text-[#6c8176] hover:text-forest"><ChevronDown size={14} className="rotate-90" /> Changer d’unité</Link><p className="eyebrow mb-2">{config.eyebrow}</p><h1 className="page-title">{config.title}</h1><p className="muted mt-2 max-w-2xl text-[13px] leading-5">{config.description}</p></div><div className="flex flex-wrap gap-2">{rangeFrom && rangeTo && onRangeChange ? <DateRangePicker from={rangeFrom} to={rangeTo} onApply={onRangeChange} /> : <PeriodSelector onChange={onPeriodChange} />}<Link href={config.actionHref} className="btn-primary"><Plus size={16} /> {config.actionLabel}</Link></div></div>;
}

function PoultryUnitDashboard({ config }: { config: UnitConfig }) {
  const [rangeFrom, setRangeFrom] = useState('2026-08-01');
  const [rangeTo, setRangeTo] = useState('2026-08-13');
  const [farmLots, setFarmLots] = useState<typeof poultryLots>([]);
  const [farmBuildings, setFarmBuildings] = useState<typeof poultryBuildings>([]);
  const [farmDailyRecords, setFarmDailyRecords] = useState<typeof poultryDailyRecords>([]);
  const [farmHealthEvents, setFarmHealthEvents] = useState<typeof poultryHealthEvents>([]);
  const [farmStock, setFarmStock] = useState<Array<{ id: string; name: string; quantity: number; min: number; unit: string; expiryDate?: string }>>([]);
  useEffect(() => {
    const load = () => {
      const snapshot = loadFarmSnapshot();
      setFarmLots(snapshot.lots);
      setFarmBuildings(snapshot.buildings);
      setFarmDailyRecords(snapshot.daily);
      setFarmHealthEvents(snapshot.health);
      setFarmStock(readLocal(FARM_STORAGE_KEYS.stock, []));
    };
    load();
    return subscribeToFarmData([
      FARM_STORAGE_KEYS.lots,
      FARM_STORAGE_KEYS.buildings,
      FARM_STORAGE_KEYS.daily,
      FARM_STORAGE_KEYS.health,
      FARM_STORAGE_KEYS.stock,
    ], load);
  }, []);
  const activeLots = farmLots.filter((lot) => lot.status !== 'Terminé' && lot.status !== 'Archivée');
  const periodRecords = farmDailyRecords.filter((record) => isDateInRange(record.date, rangeFrom, rangeTo));
  const totalAlive = activeLots.reduce((sum, lot) => sum + Number(lot.alive || 0), 0);
  const totalDeaths = farmLots.reduce((sum, lot) => sum + Math.round(Number(lot.initial || 0) * Number(lot.mortality || 0) / 100), 0);
  const averageMortality = farmLots.length ? farmLots.reduce((sum, lot) => sum + Number(lot.mortality || 0), 0) / farmLots.length : 0;
  const totalFeed = periodRecords.reduce((sum, record) => sum + Number(record.feed || 0), 0);
  const totalExpectedFeed = periodRecords.reduce((sum, record) => sum + Number(record.expectedFeed || 0), 0);
  const feedDelta = totalFeed - totalExpectedFeed;
  const totalWater = periodRecords.reduce((sum, record) => sum + Number(record.water || 0), 0);
  const latestRecord = farmDailyRecords.slice().sort((a, b) => b.date.localeCompare(a.date))[0];
  const latestWeight = latestRecord?.averageWeight ?? 0;
  const lowStock = farmStock.filter((item) => Number(item.quantity) <= Number(item.min));
  const buildingsToClean = farmBuildings.filter((building) => !['Conforme', 'Vide sanitaire'].includes(building.cleanliness));
  return <div className="fade-in space-y-7">
    <UnitHeader config={config} rangeFrom={rangeFrom} rangeTo={rangeTo} onRangeChange={(from, to) => { setRangeFrom(from); setRangeTo(to); }} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Animaux en élevage" value={String(totalAlive)} change={farmLots.length ? `${activeLots.length} bandes actives` : 'Aucune donnée'} detail="ferme de poulets" icon={PawPrint} tone="green" /><StatCard label="Bandes actives" value={String(activeLots.length)} change={farmLots.length ? 'données locales' : 'À créer'} detail="sur la ferme" icon={ClipboardCheck} tone="blue" /><StatCard label="Mortalité moyenne" value={`${averageMortality.toFixed(1).replace('.', ',')} %`} change={farmLots.length ? 'calculée' : 'À renseigner'} detail="sur les bandes" icon={AlertTriangle} tone="orange" /><StatCard label="Mortalité totale" value={`${totalDeaths} sujets`} change="quantité cumulée" detail="bandes enregistrées" icon={AlertTriangle} tone="purple" /><StatCard label="Aliment consommé" value={`${totalFeed} kg`} change="Période filtrée" detail={`${rangeFrom} → ${rangeTo}`} icon={Wheat} tone="green" /></div>
    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
      <div className="surface overflow-hidden"><div className="flex items-center justify-between border-b border-[#edf0eb] px-5 py-5 sm:px-6"><SectionHeading eyebrow="Ferme · Bâtiments" title="Occupation des bâtiments" /><ViewAll href="/poulets/batiments" label="Gérer les bâtiments" /></div><div className="grid gap-3 p-5 sm:grid-cols-3 sm:p-6">{farmBuildings.map((building) => <div className="rounded-2xl border border-[#edf0eb] bg-[#fbfcfa] p-4" key={building.id}><div className="flex items-center justify-between"><span className={`flex h-8 w-8 items-center justify-center rounded-lg ${building.status === 'Occupé' ? 'bg-[#edf8ea] text-[#5b9d5b]' : 'bg-[#fff2e2] text-[#bd7837]'}`}><PawPrint size={15} /></span><StatusBadge status={building.status} /></div><p className="mt-4 text-[12px] font-bold text-ink">{building.name}</p><p className="mt-1 text-[10px] text-[#8b9891]">{building.batch === '—' ? building.cleanliness : `${building.batch} · J${building.age}`}</p>{building.status === 'Occupé' ? <><div className="mt-4"><MiniProgress value={building.current / building.capacity * 100} color="green" label="Occupation" right={`${Math.round(building.current / building.capacity * 100)} %`} /></div><p className="mt-3 text-[10px] text-[#78877e]">{formatNumber(building.current)} / {formatNumber(building.capacity)} sujets</p></> : <div className="mt-4 rounded-lg bg-[#fff8ed] px-2.5 py-2 text-[10px] font-semibold text-[#b8793d]">{building.cleanliness}</div>}</div>)}</div></div>
      <div className="surface overflow-hidden"><div className="flex items-center justify-between border-b border-[#edf0eb] px-5 py-5"><SectionHeading eyebrow="Saisie terrain" title="Suivi du jour" /><span className="rounded-full bg-[#edf8e9] px-2.5 py-1 text-[9px] font-bold text-[#5b9d5b]">{latestRecord ? formatDate(latestRecord.date) : 'Aucune saisie'}</span></div><div className="divide-y divide-[#f0f3ef]">{periodRecords.length ? periodRecords.slice(0, 2).map((record) => <div className="px-5 py-4" key={record.id}><div className="flex items-center justify-between gap-3"><div><p className="text-[11px] font-bold text-ink">{record.building} · {record.batch}</p><p className="mt-1 text-[10px] text-[#8b9891]">Saisi par {record.recordedBy}</p></div><span className="status-badge badge-success"><Check size={12} /> Saisi</span></div><div className="mt-3 grid grid-cols-3 gap-2"><PoultryMiniMetric label="Morts" value={String(record.deaths)} tone={record.deaths > 2 ? 'red' : 'green'} /><PoultryMiniMetric label="Aliment" value={`${record.feed} kg`} /><PoultryMiniMetric label="Poids" value={`${Number(record.averageWeight || 0).toFixed(2).replace('.', ',')} kg`} /></div></div>) : <div className="px-5 py-10 text-center text-[11px] text-[#89968f]">Aucun suivi enregistré dans la période sélectionnée.</div>}</div><Link href="/poulets/suivi" className="flex items-center justify-center gap-2 border-t border-[#edf0eb] py-3 text-[11px] font-bold text-[#5c8f61]">Ouvrir la saisie quotidienne <ArrowRight size={13} /></Link></div>
    </div>
    <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]">
      <div className="surface p-5 sm:p-6"><SectionHeading eyebrow="Données enregistrées" title="Performance zootechnique" description="Les indicateurs affichés sont calculés uniquement à partir des saisies de la ferme." /><div className="mt-6 space-y-5"><PoultryProgress label="Poids moyen enregistré" value={latestRecord ? `${Number(latestWeight).toFixed(2).replace('.', ',')} kg` : 'Aucune donnée'} reference={latestRecord ? `Dernière saisie · ${formatDate(latestRecord.date)}` : 'Saisissez un poids moyen'} progress={latestRecord ? Math.min(Number(latestWeight) / 2.5 * 100, 100) : 0} color="green" /><PoultryProgress label="Aliment · réel vs attendu" value={`${formatNumber(totalFeed)} kg`} reference={`${formatNumber(totalExpectedFeed)} kg attendu`} progress={totalExpectedFeed ? Math.min(totalFeed / totalExpectedFeed * 100, 100) : 0} color="orange" /><PoultryProgress label="Eau de la période" value={`${formatNumber(totalWater)} L`} reference={`${periodRecords.length} suivi(s)`} progress={totalWater ? 100 : 0} color="blue" /></div><div className="mt-5 flex items-center gap-2 rounded-xl bg-[#f5faf2] px-3.5 py-3 text-[10px] font-semibold text-[#5b8f60]"><TrendingUp size={14} /> {totalExpectedFeed ? `Écart aliment : ${feedDelta > 0 ? '+' : ''}${formatNumber(feedDelta)} kg par rapport à l’attendu.` : 'Saisissez l’aliment attendu pour activer la comparaison.'}</div></div>
      <div className="surface p-5 sm:p-6"><SectionHeading eyebrow="Santé & biosécurité" title="Alertes de la ferme" /><div className="mt-5 space-y-3">{farmHealthEvents[0] ? <PoultryAlert title="Dernier événement sanitaire" detail={`${farmHealthEvents[0].product} · ${formatDate(farmHealthEvents[0].date)}`} tone="green" /> : <PoultryAlert title="Aucun événement sanitaire" detail="Aucune donnée enregistrée" tone="green" />}{buildingsToClean.length ? <PoultryAlert title="Nettoyage à planifier" detail={`${buildingsToClean.length} bâtiment(s) à contrôler`} tone="orange" /> : <PoultryAlert title="Biosécurité" detail={farmBuildings.length ? 'Bâtiments conformes' : 'Aucun bâtiment enregistré'} tone="green" />}{lowStock.length ? <PoultryAlert title="Stock sous le seuil" detail={`${lowStock.length} article(s) à traiter`} tone="red" /> : <PoultryAlert title="Stock ferme" detail={farmStock.length ? 'Aucune alerte de quantité' : 'Aucun article enregistré'} tone="green" />}</div><Link href="/poulets/sante" className="mt-5 flex items-center justify-center gap-2 rounded-xl border border-dashed border-[#cad8cc] py-2.5 text-[11px] font-bold text-[#5c8f61]">Ouvrir santé & biosécurité <ArrowRight size={13} /></Link></div>
    </div>
    <MortalityChart records={farmDailyRecords} from={rangeFrom} to={rangeTo} />
    <div className="surface overflow-hidden"><div className="flex items-center justify-between border-b border-[#edf0eb] px-5 py-5 sm:px-6"><SectionHeading eyebrow="Production" title="Bandes en cours" /><ViewAll href="/poulets/bandes" label="Voir toutes les bandes" /></div><div className="table-scroll"><table className="w-full text-left"><thead><tr className="table-head"><th>Bande</th><th>Bâtiment</th><th>Âge</th><th>Effectif</th><th>Poids moyen</th><th>Morts</th><th>Taux</th><th>Action</th></tr></thead><tbody>{activeLots.length ? activeLots.map((lot) => <tr className="table-row table-line" key={lot.id}><td><Link href={`/poulets/${lot.id}`} className="font-bold text-ink hover:text-[#579b5b]">{lot.id}</Link><p className="mt-1 text-[10px] text-[#9aa59f]">{lot.name}</p></td><td>{farmBuildings.find((building) => building.batch === lot.id)?.name ?? 'Non affectée'}</td><td>J{lot.age}</td><td className="font-bold text-ink">{formatNumber(lot.alive)}</td><td>{Number(lot.weight || 0).toFixed(2).replace('.', ',')} kg</td><td><strong className="text-ink">{Math.round(Number(lot.initial || 0) * Number(lot.mortality || 0) / 100)}</strong></td><td><span className={lot.mortality > 4 ? 'font-bold text-[#c76662]' : 'font-semibold text-[#5b9d5b]'}>{formatPercent(lot.mortality)}</span></td><td><Link href={`/poulets/${lot.id}`} className="icon-btn h-8 w-8"><ArrowRight size={14} /></Link></td></tr>) : <tr><td colSpan={8} className="px-6 py-12 text-center text-[11px] text-[#89968f]">Aucune bande active enregistrée.</td></tr>}</tbody></table></div></div>
    <div className="grid gap-5 lg:grid-cols-3"><FarmAction href="/poulets/suivi" icon={ClipboardCheck} title="Suivi quotidien" text="Consulter la mortalité, l’aliment, l’eau, le poids et l’ambiance." /><FarmAction href="/poulets/transferts" icon={ArrowLeftRight} title="Transférer des sujets" text="Déplacer une partie d’une bande entre bâtiments." /><FarmAction href="/factures" icon={Receipt} title="Ventes de la ferme" text="Factures et paiements propres à l’unité ferme." /></div>
  </div>;
}

function MortalityChart({ records, from, to }: { records: typeof poultryDailyRecords; from: string; to: string }) {
  const source = records.filter((record) => isDateInRange(record.date, from, to));
  const points = source.slice().reverse().map((record, index) => ({ label: `${formatDate(record.date).slice(0, 5)} · ${record.building.slice(-1)}`, actual: record.deaths, expected: record.expectedDeaths }));
  const max = Math.max(...points.flatMap((point) => [point.actual, point.expected]), 4);
  const pointString = (key: 'actual' | 'expected') => points.map((point, index) => `${points.length === 1 ? 50 : (index / (points.length - 1)) * 100},${92 - (point[key] / max) * 70}`).join(' ');
  return <div className="surface p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><SectionHeading eyebrow="Suivi du jour" title="Mortalité · réel vs attendu" description="Comparez ce qui était prévu avec ce qui a réellement été enregistré." /><div className="flex gap-4 text-[10px] font-bold"><span className="flex items-center gap-1.5 text-[#c9786d]"><i className="h-2 w-2 rounded-full bg-[#d9706b]" /> Réel</span><span className="flex items-center gap-1.5 text-[#5b9d5b]"><i className="h-2 w-2 rounded-full bg-[#71bd76]" /> Attendu</span></div></div><div className="mt-6 flex h-[190px] gap-4"><div className="flex flex-col justify-between pb-5 text-[10px] font-medium text-[#a0aaa4]"><span>{max}</span><span>{Math.round(max / 2)}</span><span>0</span></div><div className="relative min-w-0 flex-1"><div className="absolute inset-x-0 top-0 border-t border-dashed border-[#e8ede7]" /><div className="absolute inset-x-0 top-1/2 border-t border-dashed border-[#e8ede7]" /><div className="absolute inset-x-0 bottom-5 border-t border-[#e8ede7]" /><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="absolute inset-0 h-[165px] w-full overflow-visible"><polyline points={pointString('expected')} fill="none" stroke="#71bd76" strokeWidth="1.8" vectorEffect="non-scaling-stroke" strokeDasharray="4 4" /><polyline points={pointString('actual')} fill="none" stroke="#d9706b" strokeWidth="2.2" vectorEffect="non-scaling-stroke" />{points.map((point, index) => <circle key={`actual-${index}`} cx={points.length === 1 ? 50 : (index / (points.length - 1)) * 100} cy={92 - (point.actual / max) * 70} r="2.2" fill="#d9706b" vectorEffect="non-scaling-stroke" />)}</svg><div className="absolute inset-x-0 bottom-0 flex justify-between text-[9px] font-medium text-[#9aa59f]">{points.map((point) => <span key={point.label}>{point.label}</span>)}</div></div></div><div className="mt-4 flex items-center gap-2 rounded-xl bg-[#fff8ed] px-3.5 py-3 text-[10px] font-semibold text-[#a86f3c]"><AlertTriangle size={14} /> Une saisie avec une mortalité supérieure à l’attendu déclenche une alerte à traiter.</div></div>;
}

function isDateInRange(date: string, from: string, to: string) { return date >= from && date <= to; }

function PoultryMiniMetric({ label, value, tone = 'default' }: { label: string; value: string; tone?: 'default' | 'green' | 'red' }) { return <div className="rounded-lg bg-[#f6f8f4] px-2.5 py-2"><p className="text-[9px] font-semibold text-[#8b9891]">{label}</p><p className={`mt-1 text-[11px] font-black ${tone === 'red' ? 'text-[#c76662]' : tone === 'green' ? 'text-[#5b9d5b]' : 'text-ink'}`}>{value}</p></div>; }
function PoultryProgress({ label, value, reference, progress, color }: { label: string; value: string; reference: string; progress: number; color: 'green' | 'orange' | 'blue' }) { return <div><div className="mb-2 flex items-end justify-between gap-3"><div><p className="text-[11px] font-bold text-ink">{label}</p><p className="mt-1 text-[10px] text-[#8b9891]">{reference}</p></div><span className="text-[12px] font-black text-ink">{value}</span></div><MiniProgress value={progress} color={color} /></div>; }
function PoultryAlert({ title, detail, tone }: { title: string; detail: string; tone: 'green' | 'orange' | 'red' }) { const styles = { green: 'bg-[#edf8ea] text-[#5b9d5b]', orange: 'bg-[#fff2e2] text-[#bd7737]', red: 'bg-[#fdeceb] text-[#bd5c5c]' }; return <div className="flex items-center gap-3 rounded-xl border border-[#edf0eb] p-3"><span className={`flex h-8 w-8 items-center justify-center rounded-lg ${styles[tone]}`}>{tone === 'green' ? <Check size={15} /> : <AlertTriangle size={15} />}</span><div><p className="text-[11px] font-bold text-ink">{title}</p><p className="mt-1 text-[10px] text-[#8b9891]">{detail}</p></div></div>; }
function FarmAction({ href, icon: Icon, title, text }: { href: string; icon: LucideIcon; title: string; text: string }) { return <Link href={href} className="group surface flex items-start gap-3 p-5 transition hover:-translate-y-0.5 hover:border-[#cde3cc]"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[#edf8ea] text-[#5b9d5b]"><Icon size={16} /></span><span className="min-w-0 flex-1"><span className="block text-[12px] font-bold text-ink">{title}</span><span className="mt-1 block text-[10px] leading-4 text-[#87958d]">{text}</span></span><ArrowRight size={14} className="mt-1 text-[#a0aaa4] transition group-hover:translate-x-1 group-hover:text-[#5b9d5b]" /></Link>; }

function FeedUnitDashboard({ config }: { config: UnitConfig }) { return <UnitDashboardShell config={config} stats={[['Production du mois', '4 200 kg', '+16,2 %', 'green', Wheat], ['Recettes actives', '06', '2 élevages', 'blue', ClipboardCheck], ['Coût moyen / kg', formatFCFA(575), '-4,1 %', 'orange', CircleDollarSign], ['Matières critiques', '02', 'À traiter', 'purple', Package]]} title="Productions récentes"><div className="grid gap-4 md:grid-cols-3">{feedProductions.map((item) => <div className="rounded-2xl border border-[#edf0eb] bg-[#fbfcfa] p-4" key={item.id}><div className="flex items-center justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#fff3e4] text-[#be7839]"><Wheat size={17} /></span><StatusBadge status={item.status} /></div><p className="mt-4 text-[12px] font-bold text-ink">{item.recipe}</p><p className="mt-1 text-[10px] text-[#8b9891]">{formatDate(item.date)} · {formatNumber(item.quantity)} {item.unit}</p><div className="mt-4"><MiniProgress value={item.status === 'Disponible' ? 100 : 72} color="orange" label="Disponibilité" right={item.status === 'Disponible' ? '100%' : '72%'} /></div></div>)}</div></UnitDashboardShell>; }
function BioUnitDashboard({ config }: { config: UnitConfig }) { return <UnitDashboardShell config={config} stats={[['Fabrication du mois', '950 kg/L', '+21,5 %', 'green', FlaskConical], ['Recettes bio actives', '05', '3 produits', 'blue', ClipboardCheck], ['Coût moyen', formatFCFA(618), '-3,2 %', 'orange', CircleDollarSign], ['Lots approvisionnés', '04', 'Élevage poulets', 'purple', PawPrint]]} title="Fabrications récentes"><div className="grid gap-4 md:grid-cols-3">{bioProductions.map((item) => <div className="rounded-2xl border border-[#edf0eb] bg-[#fbfcfa] p-4" key={item.id}><div className="flex items-center justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#edf8ea] text-[#579b5a]"><FlaskConical size={17} /></span><StatusBadge status={item.status} /></div><p className="mt-4 text-[12px] font-bold text-ink">{item.product}</p><p className="mt-1 text-[10px] text-[#8b9891]">{item.target} · {formatNumber(item.quantity)} {item.unit}</p><p className="mt-4 text-[11px] font-bold text-[#5b9d5b]">{formatFCFA(item.cost)} <span className="font-medium text-[#91a098]">coût</span></p></div>)}</div></UnitDashboardShell>; }
function PressUnitDashboard({ config }: { config: UnitConfig }) { return <UnitDashboardShell config={config} stats={[['Huile produite', '1 941 L', '+12,4 %', 'green', Droplets], ['Tourteaux', '3 465 kg', '+9,8 %', 'blue', Wheat], ['Rendement moyen', '33,1 %', '+1,4 pt', 'orange', TrendingUp], ['Lots pressés', '03', 'Ce mois-ci', 'purple', ClipboardCheck]]} title="Lots de pressage"><div className="grid gap-4 md:grid-cols-3">{oilProductions.map((item) => <div className="rounded-2xl border border-[#edf0eb] bg-[#fbfcfa] p-4" key={item.id}><div className="flex items-center justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#fff6d8] text-[#ac861f]"><Droplets size={17} /></span><span className="text-[12px] font-bold text-[#5b9d5b]">{item.yield}%</span></div><p className="mt-4 text-[12px] font-bold text-ink">{item.seed} · {item.id}</p><p className="mt-1 text-[10px] text-[#8b9891]">{formatDate(item.date)} · {formatNumber(item.input)} kg entrée</p><div className="mt-4"><MiniProgress value={item.yield * 2.3} color="orange" label="Rendement huile" right={`${item.yield}%`} /></div></div>)}</div></UnitDashboardShell>; }
function StockUnitDashboard({ config }: { config: UnitConfig }) { return <UnitDashboardShell config={config} stats={[['Valeur du stock', formatFCFA(7420000, true), '+8,4 %', 'green', Package], ['Références actives', '128', '+12', 'blue', Boxes], ['Stock critique', '02', 'À traiter', 'orange', ClipboardCheck], ['Mouvements', '86', 'Ce mois-ci', 'purple', TrendingUp]]} title="État du stock"><div className="grid gap-3 md:grid-cols-2">{inventory.slice(0, 4).map((item) => <div className="flex items-center gap-3 rounded-2xl border border-[#edf0eb] bg-[#fbfcfa] p-4" key={item.id}><span className="h-9 w-1.5 rounded-full" style={{ background: item.color }} /><div className="min-w-0 flex-1"><p className="truncate text-[12px] font-bold text-ink">{item.name}</p><p className="mt-1 text-[10px] text-[#8b9891]">{item.quantity} {item.unit} · {item.location}</p></div><StatusBadge status={item.status} /></div>)}</div></UnitDashboardShell>; }

function UnitDashboardShell({ config, stats, title, children }: { config: UnitConfig; stats: [string, string, string, 'green' | 'blue' | 'orange' | 'purple', LucideIcon][]; title: string; children: React.ReactNode }) { return <div className="fade-in space-y-7"><UnitHeader config={config} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label, value, change, tone, Icon]) => <StatCard key={label} label={label} value={value} change={change} detail={label.includes('coût') || label.includes('Coût') ? 'ce mois-ci' : 'vs. période précédente'} icon={Icon} tone={tone} />)}</div><div className="surface overflow-hidden p-5 sm:p-6"><div className="flex items-end justify-between"><SectionHeading eyebrow={config.eyebrow} title={title} /><ViewAll href={config.actionHref} label="Voir tout" /></div><div className="mt-5">{children}</div></div><div className="grid gap-5 lg:grid-cols-2"><div className="surface p-5 sm:p-6"><SectionHeading eyebrow="Raccourcis" title="Actions de l’unité" /><div className="mt-5 grid gap-2 sm:grid-cols-2"><QuickLink href={config.actionHref} label={config.actionLabel} icon={config.icon} /><QuickLink href="/mouvements" label="Voir les mouvements" icon={ArrowRight} /><QuickLink href="/factures" label="Voir les factures" icon={Receipt} /><QuickLink href="/rapports" label="Ouvrir les rapports" icon={BarChart3} /></div></div><div className="surface bg-forest p-5 text-white sm:p-6"><p className="eyebrow text-[#91af9f]">Périmètre actif</p><h2 className="mt-2 text-[20px] font-bold tracking-[-.04em]">Les données restent propres à cette unité.</h2><p className="mt-2 text-[11px] leading-5 text-[#a8c4ae]">Les échanges avec les autres activités de SCOOPS LE REVEIL passent uniquement par les mouvements inter-unités.</p><Link href="/selection-unite" className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[#a4eb91] px-3.5 py-2.5 text-[11px] font-bold text-forest">Changer d’unité <ArrowRight size={14} /></Link></div></div></div>; }
function QuickLink({ href, label, icon: Icon }: { href: string; label: string; icon: LucideIcon }) { return <Link href={href} className="flex items-center gap-2 rounded-xl border border-[#edf0eb] px-3 py-3 text-[11px] font-bold text-[#66766d] transition hover:border-[#cde3cc] hover:bg-[#f8fcf6] hover:text-forest"><Icon size={15} />{label}<ArrowRight size={13} className="ml-auto text-[#9eaaa2]" /></Link>; }
function AlertRow({ title, detail, tone }: { title: string; detail: string; tone: 'red' | 'orange' | 'green' }) { const cls = { red: 'bg-[#fdeceb] text-[#bd5c5c]', orange: 'bg-[#fff2e2] text-[#c07839]', green: 'bg-[#edf8ea] text-[#5b9d5b]' }; return <div className="flex items-center gap-3 rounded-xl border border-[#edf0eb] p-3"><span className={`flex h-8 w-8 items-center justify-center rounded-lg ${cls[tone]}`}><ClipboardCheck size={15} /></span><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-bold text-ink">{title}</p><p className="mt-1 text-[10px] text-[#8b9891]">{detail}</p></div></div>; }
function FarmKpi({ title, value, progress, color, hint }: { title: string; value: string; progress: number; color: 'green' | 'orange' | 'blue'; hint: string }) { return <div className="surface p-5"><p className="text-[11px] font-semibold text-[#78867e]">{title}</p><p className="mt-2 text-[24px] font-black tracking-[-.055em] text-ink">{value}</p><div className="mt-4"><MiniProgress value={progress} color={color} /></div><p className="mt-2 text-[10px] text-[#8b9891]">{hint}</p></div>; }

