import type { InvoicePdfData } from '@/lib/invoice-pdf';

export function openInvoicePrint(invoice: InvoicePdfData, language: 'fr' | 'en' = 'fr') {
  const en = language === 'en';
  const labels = en ? { invoice: 'INVOICE', date: 'Date', unit: 'Unit', customer: 'CUSTOMER', description: 'Description', category: 'Category', quantity: 'Qty', unitPrice: 'Unit price', amount: 'Amount', subtotal: 'Subtotal', tax: 'Tax', total: 'TOTAL', payment: 'Payment received', balance: 'Balance due', status: 'Status', method: 'Payment method', thanks: 'Thank you for your trust.' } : { invoice: 'FACTURE', date: 'Date', unit: 'Unité', customer: 'CLIENT', description: 'Description', category: 'Catégorie', quantity: 'Qté', unitPrice: 'Prix unitaire', amount: 'Montant', subtotal: 'Sous-total', tax: 'TVA', total: 'TOTAL TTC', payment: 'Versement', balance: 'Reste à payer', status: 'Statut', method: 'Mode de paiement', thanks: 'Merci pour votre confiance.' };
  const rows = invoice.lines.map((line) => `<tr><td>${escapeHtml(line.description)}</td><td>${escapeHtml(invoice.poultryCategory ?? (en ? 'Poultry' : 'Poulet'))}</td><td>${line.quantity} ${escapeHtml(line.unit)}</td><td>${format(line.unitPrice)} FCFA</td><td>${format(line.total)} FCFA</td></tr>`).join('');
  const html = `<!doctype html><html lang="${language}"><head><meta charset="utf-8"><title>${invoice.id}</title><style>@page{size:A4;margin:15mm}*{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;color:#1d2e27;margin:0;font-size:12px}header{display:flex;justify-content:space-between;border-bottom:3px solid #9be789;padding-bottom:18px;margin-bottom:24px}.brand{font-size:22px;font-weight:800;letter-spacing:-1px}.brand span{color:#5b9d5b}.muted{color:#738179;font-size:11px;line-height:1.6}.right{text-align:right}.box{background:#f4faf2;border-radius:8px;padding:12px;margin-bottom:18px}table{border-collapse:collapse;width:100%;margin-top:18px}th{background:#19382e;color:#fff;text-align:left;font-size:10px;padding:9px}td{border-bottom:1px solid #e5ece4;padding:10px;font-size:11px}td:nth-child(n+3),th:nth-child(n+3){text-align:right}.summary{margin-left:auto;margin-top:20px;width:280px}.summary div{display:flex;justify-content:space-between;padding:5px 0}.summary .total{border-top:1px solid #dfe8df;margin-top:8px;padding-top:10px;font-size:15px;font-weight:800}.foot{border-top:1px solid #e5ece4;margin-top:80px;padding-top:12px;color:#89968f;font-size:10px}</style></head><body><header><div><div class="brand">agro<span>flux</span></div><div class="muted">SCOOPS LE REVEIL<br>Yaoundé, Cameroun<br>+237 6 70 00 12 45</div></div><div class="right"><h1>${labels.invoice}</h1><strong>${escapeHtml(invoice.id)}</strong><div class="muted">${labels.date} : ${escapeHtml(invoice.issueDate)}<br>${labels.unit} : ${escapeHtml(invoice.unitLabel)}</div></div></header><div class="box"><strong>${labels.customer}</strong><br>${escapeHtml(invoice.customer || (en ? 'Customer not specified' : 'Client non renseigné'))}${invoice.customerType ? `<br><span class="muted">${en ? 'Type' : 'Type'} : ${escapeHtml(invoice.customerType)}</span>` : ''}${invoice.building ? `<br><span class="muted">${en ? 'Building' : 'Bâtiment'} : ${escapeHtml(invoice.building)}</span>` : ''}</div><table><thead><tr><th>${labels.description}</th><th>${labels.category}</th><th>${labels.quantity}</th><th>${labels.unitPrice}</th><th>${labels.amount}</th></tr></thead><tbody>${rows}</tbody></table><div class="summary"><div><span>${labels.subtotal}</span><strong>${format(invoice.subtotal)} FCFA</strong></div><div><span>${labels.tax} (${invoice.taxRate} %)</span><strong>${format(invoice.tax)} FCFA</strong></div><div class="total"><span>${labels.total}</span><strong>${format(invoice.total)} FCFA</strong></div><div><span>${labels.payment}</span><strong>${format(invoice.paid)} FCFA</strong></div><div><span>${labels.balance}</span><strong>${format(invoice.remaining)} FCFA</strong></div><div><span>${labels.status}</span><strong>${escapeHtml(invoice.status)}</strong></div><div><span>${labels.method}</span><strong>${escapeHtml(invoice.paymentMethod || (en ? 'Not specified' : 'Non renseigné'))}</strong></div></div><div class="foot">${labels.thanks}<br>AgroFlux · SCOOPS LE REVEIL</div></body></html>`;
  const printWindow = window.open('', '_blank', 'width=900,height=700');
  if (!printWindow) return;
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.onload = () => window.setTimeout(() => { printWindow.focus(); printWindow.print(); }, 300);
}
function format(value: number) { return new Intl.NumberFormat('fr-FR').format(Math.round(value)); }
function escapeHtml(value: string) { return value.replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char] ?? char)); }
